[[faq]]
= Frequently Asked Questions

This section covers the following content:

* <<faq.proxy-connect-method>>
* <<faq.logging-prefix>>
* <<faq.logging-correlation>>
* <<faq.connection-closed>>

[[faq.proxy-connect-method]]
== Connection to the proxy cannot be established
include::proxy.adoc[tag=proxy-connect-method]

[[faq.logging-prefix]]
== What is it meaning of the information that is prepended to every log record?
Reactor Netty adds information for the connection at the beginning of every log record (when this is possible).
There is a slight difference in the details for the connection when you use `TCP`, `UDP`, `HTTP/1.1` or `HTTP/2`.

=== TCP and UDP
In case of `TCP` and `UDP`, the following is added at the beginning of every log record: the id of the underlying connection, local and remote addresses.

====
[source,text,indent=0]
----
Examples
[a1566d55, L:/[0:0:0:0:0:0:0:1]:53446 - R:/[0:0:0:0:0:0:0:1]:53444]
[a1566d55, L:/[0:0:0:0:0:0:0:1]:53446 ! R:/[0:0:0:0:0:0:0:1]:53444]

Format
[<CONNECTION_ID>, L:<LOCAL_ADDRESS> <CONNECTION_OPENED_CLOSED> R:<REMOTE_ADDRESS>]
<CONNECTION_ID>: a1566d55
<LOCAL_ADDRESS>: [0:0:0:0:0:0:0:1]:53446
<CONNECTION_OPENED_CLOSED>: - (connection opened)
                            ! (connection closed)
<REMOTE_ADDRESS>: [0:0:0:0:0:0:0:1]:53444
----
====

=== HTTP/1.1
In case of `HTTP/1.1`, the following is added at the beginning of every log record: the id of the underlying connection,
the serial number of the request received on that connection, local and remote addresses.

====
[source,text,indent=0]
----
Examples
[a1566d55-5, L:/[0:0:0:0:0:0:0:1]:53446 - R:/[0:0:0:0:0:0:0:1]:53444]
[a1566d55-5, L:/[0:0:0:0:0:0:0:1]:53446 ! R:/[0:0:0:0:0:0:0:1]:53444]

Format
[<CONNECTION_ID>-<REQUEST_NUMBER>, L:<LOCAL_ADDRESS> <CONNECTION_OPENED_CLOSED> R:<REMOTE_ADDRESS>]
<CONNECTION_ID>: a1566d55
<REQUEST_NUMBER>: 5
<LOCAL_ADDRESS>: [0:0:0:0:0:0:0:1]:53446
<CONNECTION_OPENED_CLOSED>: - (connection opened)
                            ! (connection closed)
<REMOTE_ADDRESS>: [0:0:0:0:0:0:0:1]:53444
----
====

=== HTTP/2
In case of `HTTP/2`, the following is added at the beginning of every log record: the id of the underlying connection,
local and remote addresses, the id of the stream received on that connection.

====
[source,text,indent=0]
----
Examples
[a1566d55, L:/[0:0:0:0:0:0:0:1]:53446 - R:/[0:0:0:0:0:0:0:1]:53444](H2 - 5)
[a1566d55, L:/[0:0:0:0:0:0:0:1]:53446 ! R:/[0:0:0:0:0:0:0:1]:53444](H2 - 5)

Format
[<CONNECTION_ID>, L:<LOCAL_ADDRESS> <CONNECTION_OPENED_CLOSED> R:<REMOTE_ADDRESS>]<STREAM_ID>
<CONNECTION_ID>: a1566d55
<LOCAL_ADDRESS>: [0:0:0:0:0:0:0:1]:53446
<CONNECTION_OPENED_CLOSED>: - (connection opened)
                            ! (connection closed)
<REMOTE_ADDRESS>: [0:0:0:0:0:0:0:1]:53444
<STREAM_ID>: (H2 - 5)
----
====

[[faq.logging-correlation]]
== How can I extract all log records for a particular HTTP request?
Reactor Netty adds information for the connection at the beginning of every log record (when this is possible).
Use the id of the connection in order to extract all log records for a particular HTTP request.
For more information see <<faq.logging-prefix>>

[[faq.connection-closed]]
== How can I debug "Connection prematurely closed BEFORE response"?
By default, Reactor Netty clients use a connection pooling. When a connection is acquired from the connection pool, it is checked whether it is still opened.
However, the connection can be closed at any time after the acquisition. There are many reasons that can cause connection to be closed.
In most cases the setup might not be like: the client directly sends to the server, but there might be many other network components between them: proxies, load balancers etc.

If on the client side you observe `Connection prematurely closed BEFORE response`, perform the checks below to identify the reason for the connection close:

* Obtain https://en.wikipedia.org/wiki/Tcpdump[tcp dump] and check which peer sends `FIN`/`RST` signal
* Check your network connection
* Check your Firewall/VPN
* Check for any proxies and load balancers. Do they have some kind of idle timeout configuration? (the connection is closed when there is no incoming data for a certain period of time)
* Check the target server. Are there configurations related to:
** idle timeout (the connection is closed when there is no incoming data for a certain period of time)
** limit for buffering data in memory
** multipart exceeds the max file size limit
** bad request

Consider checking <<Timeout Configuration>>. The section describes various timeout configuration options available for Reactor Netty clients.
Configuring a proper timeout may improve or solve issues in the communication process.
