:sourcedir: ./../../reactor-netty-http/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client
:javadoc: https://projectreactor.io/docs/netty/release/api
:nettyjavadoc: https://netty.io/4.1/api

[[http-client]]
= HTTP Client

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/http/client/HttpClient.html[`HttpClient`].
It hides most of the Netty functionality that is required to create a `HTTP` client
and adds Reactive Streams backpressure.

== Connect

To connect the `HTTP` client to a given `HTTP` endpoint, you must create and configure a
{javadoc}/reactor/netty/http/client/HttpClient.html[`HttpClient`] instance.
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/connect/Application.java
----
include::{examplesdir}/connect/Application.java[lines=18..30]
----
<1> Creates a {javadoc}/reactor/netty/http/client/HttpClient.html[HttpClient]
instance ready for configuring.
<2> Specifies that `GET` method will be used.
<3> Specifies the path.
<4> Obtains the response {javadoc}/reactor/netty/http/client/HttpClientResponse.html[HttpClientResponse]
====


The following example uses `WebSocket`:

====
[source,java,indent=0]
.{examplesdir}/websocket/Application.java
----
include::{examplesdir}/websocket/Application.java[lines=18..42]
----
====

=== Host and Port

In order to connect to a specific host and port, you can apply the following configuration to the `HTTP` client:

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..33]
----
<1> Configures the `HTTP` host
<2> Configures the `HTTP` port
====

== Eager Initialization

By default, the initialization of the `HttpClient` resources happens on demand. This means that the `first
request` absorbs the extra time needed to initialize and load:

 * the event loop group
 * the host name resolver
 * the native transport libraries (when native transport is used)
 * the native libraries for the security (in case of `OpenSsl`)

When you need to preload these resources, you can configure the `HttpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/warmup/Application.java
----
include::{examplesdir}/warmup/Application.java[lines=18..36]
----
<1> Initialize and load the event loop group, the host name resolver, the native transport libraries and
the native libraries for the security
<2> Host name resolution happens with the first request.
In this example, a connection pool is used, so with the first request the connection to the URL is established,
the subsequent requests to the same URL reuse the connections from the pool.
====

== Writing Data

To send data to a given `HTTP` endpoint, you can provide a `Publisher` by using the
{javadoc}/reactor/netty/http/client/HttpClient.RequestSender.html#send-org.reactivestreams.Publisher-[`send(Publisher)`] method.
By default, `Transfer-Encoding: chunked` is applied for those `HTTP` methods for which
a request body is expected. `Content-Length` provided through request headers disables `Transfer-Encoding: chunked`,
if necessary. The following example sends `hello`:

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..33]
----
<1> Sends a `hello` string to the given `HTTP` endpoint
====

=== Adding Headers and Other Metadata

When sending data to a given `HTTP` endpoint, you may need to send additional headers, cookies and other metadata.
You can use the following configuration to do so:

====
[source,java,indent=0]
.{examplesdir}/send/headers/Application.java
----
include::{examplesdir}/send/headers/Application.java[lines=18..36]
----
<1> Disables `Transfer-Encoding: chunked` and provides `Content-Length` header.
====

==== Compression

You can enable compression on the `HTTP` client, which means the request header
`Accept-Encoding` is added to the request headers. The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/compression/Application.java
----
include::{examplesdir}/compression/Application.java[lines=18..32]
----
====

==== Auto-Redirect Support

You can configure the `HTTP` client to enable auto-redirect support.

Reactor Netty provides two different strategies for auto-redirect support:

* `followRedirect(boolean)`: Specifies whether HTTP auto-redirect support is enabled for statuses `301|302|307|308`.
* `followRedirect(BiPredicate<HttpClientRequest, HttpClientResponse>)`: Enables auto-redirect support if the supplied
predicate matches.

The following example uses `followRedirect(true)`:

====
[source,java,indent=0]
.{examplesdir}/redirect/Application.java
----
include::{examplesdir}/redirect/Application.java[lines=18..32]
----
====

== Consuming Data

To receive data from a given `HTTP` endpoint, you can use one of the methods from
{javadoc}/reactor/netty/http/client/HttpClient.ResponseReceiver.html[`HttpClient.ResponseReceiver`].
The following example uses the `responseContent` method:

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..33]
----
<1> Receives data from a given `HTTP` endpoint
<2> Aggregates the data
<3> Transforms the data as string
====

=== Reading Headers and Other Metadata

When receiving data from a given `HTTP` endpoint, you can check response headers, status code, and other metadata.
You can obtain this additional metadata by using
{javadoc}/reactor/netty/http/client/HttpClientResponse.html[`HttpClientResponse`].
The following example shows how to do so.

====
[source,java,indent=0]
.{examplesdir}/read/status/Application.java
----
include::{examplesdir}/read/status/Application.java[lines=18..34]
----
<1> Obtains the status code.
====

=== HTTP Response Decoder

By default, `Netty` configures some restrictions for the incoming responses, such as:

* The maximum length of the initial line.
* The maximum length of all headers.
* The maximum length of the content or each chunk.

For more information, see {nettyjavadoc}/io/netty/handler/codec/http/HttpResponseDecoder.html[HttpResponseDecoder]

By default, the `HTTP` client is configured with the following settings:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/HttpDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/HttpDecoderSpec.java[lines=29..33]
----
====
====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/client/HttpResponseDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/client/HttpResponseDecoderSpec.java[lines=35..43]
----
====

When you need to change these default settings, you can configure the `HTTP` client as follows:

====
[source,java,indent=0]
.{examplesdir}/responsedecoder/Application.java
----
include::{examplesdir}/responsedecoder/Application.java[lines=18..35]
----
<1> The maximum length of all headers will be `16384`.
When this value is exceeded, a
{nettyjavadoc}/io/netty/handler/codec/TooLongFrameException.html[TooLongFrameException]
is raised.
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `HttpClient`.

[width="100%",options="header"]
|=======
| Callback | Description
| `doAfterRequest` | Invoked when the request has been sent.
| `doAfterResolve` | Invoked after the remote address has been resolved successfully.
| `doAfterResponseSuccess` | Invoked after the response has been fully received.
| `doOnChannelInit` | Invoked when initializing the channel.
| `doOnConnect` | Invoked when the channel is about to connect.
| `doOnConnected` | Invoked after the channel has been connected.
| `doOnDisconnected` | Invoked after the channel has been disconnected.
| `doOnError` | Invoked when the request has not been sent and when the response has not been fully received.
| `doOnRedirect` | Invoked when the response headers have been received, and the request is about to be redirected.
| `doOnRequest` | Invoked when the request is about to be sent.
| `doOnRequestError` | Invoked when the request has not been sent.
| `doOnResolve` | Invoked when the remote address is about to be resolved.
| `doOnResolveError` | Invoked in case the remote address hasn't been resolved successfully.
| `doOnResponse` | Invoked after the response headers have been received.
| `doOnResponseError` | Invoked when the response has not been fully received.
|=======

The following example uses the `doOnConnected` and `doOnChannelInit` callbacks:

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..39]
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when the channel has been connected.
<2> `Netty` pipeline is extended with `LoggingHandler` when initializing the channel.
====

== TCP-level Configuration

When you need configurations on a TCP level, you can use the following snippet
to extend the default `TCP` client configuration (add an option, bind address etc.):

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..40]
----
====

See <<tcp-client>> for more about `TCP` level configurations.

=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers needs to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.http.client.HttpClient` level to `DEBUG`
and apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..32]
----
<1> Enables the wire logging
====

By default, the wire logging uses {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#HEX_DUMP[AdvancedByteBufFormat#HEX_DUMP]
when printing the content.
When you need to change this to {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#SIMPLE[AdvancedByteBufFormat#SIMPLE]
or {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL],
you can configure the `HttpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/wiretap/custom/Application.java
----
include::{examplesdir}/wiretap/custom/Application.java[lines=18..34]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL] is used for
printing the content.
====

== SSL and TLS
When you need SSL or TLS, you can apply the configuration shown in the next example.
By default, if `OpenSSL` is available, a
{nettyjavadoc}/io/netty/handler/ssl/SslProvider.html#OPENSSL[SslProvider.OPENSSL]
provider is used as a provider. Otherwise a
{nettyjavadoc}/io/netty/handler/ssl/SslProvider.html#JDK[SslProvider.JDK] provider is used
You can switch the provider by using
{nettyjavadoc}/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[SslContextBuilder]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.
The following example uses `SslContextBuilder`:

====
[source,java,indent=0]
.{examplesdir}/security/Application.java
----
include::{examplesdir}/security/Application.java[lines=18..35]
----
====

=== Server Name Indication
By default, the `HTTP` client sends the remote host name as `SNI` server name.
When you need to change this default setting, you can configure the `HTTP` client as follows:

====
[source,java,indent=0]
.{examplesdir}/sni/Application.java
----
include::{examplesdir}/sni/Application.java[lines=18..39]
----
====

== Retry Strategies
By default, the `HTTP` client retries the request once if it was aborted on the `TCP` level.

== HTTP/2

By default, the `HTTP` client supports `HTTP/1.1`. If you need `HTTP/2`, you can get it through configuration.
In addition to the protocol configuration, if you need `H2` but not `H2C (cleartext)`, you must also configure SSL.

NOTE: As Application-Layer Protocol Negotiation (ALPN) is not supported "`out-of-the-box`" by JDK8 (although some vendors backported ALPN to JDK8), you need an additional dependency to a native library that
supports it -- for example, https://netty.io/wiki/forked-tomcat-native.html[`netty-tcnative-boringssl-static`].

The following listing presents a simple `H2` example:

====
[source,java,indent=0]
.{examplesdir}/http2/H2Application.java
----
include::{examplesdir}/http2/H2Application.java[lines=18..42]
----
<1> Configures the client to support only `HTTP/2`
<2> Configures `SSL`
====

The following listing presents a simple `H2C` example:

====
[source,java,indent=0]
.{examplesdir}/http2/H2CApplication.java
----
include::{examplesdir}/http2/H2CApplication.java[lines=18..41]
----
====

=== Protocol Selection

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/HttpProtocol.java
----
include::{sourcedir}/reactor/netty/http/HttpProtocol.java[lines=24..52]
----
====

== Metrics
The HTTP client supports built-in integration with https://micrometer.io/[`Micrometer`].
It exposes all metrics with a prefix of `reactor.netty.http.client`.

The following table provides information for the HTTP client metrics:

[width="100%",options="header"]
|=======
| metric name | type | description
| reactor.netty.http.client.data.received | DistributionSummary | Amount of the data received, in bytes
| reactor.netty.http.client.data.sent | DistributionSummary | Amount of the data sent, in bytes
| reactor.netty.http.client.errors | Counter | Number of errors that occurred
| reactor.netty.http.client.tls.handshake.time | Timer | Time spent for TLS handshake
| reactor.netty.http.client.connect.time | Timer | Time spent for connecting to the remote address
| reactor.netty.http.client.address.resolver | Timer | Time spent for resolving the address
| reactor.netty.http.client.data.received.time | Timer | Time spent in consuming incoming data
| reactor.netty.http.client.data.sent.time | Timer | Time spent in sending outgoing data
| reactor.netty.http.client.response.time | Timer | Total time for the request/response
|=======

These additional metrics are also available:

include::conn-provider-metrics.adoc[]

include::alloc-metrics.adoc[]

The following example enables that integration:

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..51]
----
<1> Applies upper limit for the meters with `URI` tag
<2> Templated URIs will be used as an URI tag value when possible
<3> Enables the built-in integration with Micrometer
====

NOTE: In order to avoid a memory and CPU overhead of the enabled metrics, it is important to convert the real URIs to templated URIs when possible.
Without a conversion to a template-like form, each distinct URI leads to the creation of a distinct tag, which takes a lot of memory for the metrics.

NOTE: Always apply an upper limit for the meters with URI tags. Configuring an upper limit on the number of meters can help in cases when the real URIs cannot be templated.
You can find more information at https://micrometer.io/docs/concepts#_denyaccept_meters[`maximumAllowableTags`].

When HTTP client metrics are needed for an integration with a system other than `Micrometer` or you want
to provide your own integration with `Micrometer`, you can provide your own metrics recorder, as follows:

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..35]
----
<1> Enables HTTP client metrics and provides {javadoc}/reactor/netty/http/client/HttpClientMetricsRecorder.html[`HttpClientMetricsRecorder`] implementation.
====

== Unix Domain Sockets
The `HTTP` client supports Unix Domain Sockets (UDS) when native transport is in use.

The following example shows how to use UDS support:

====
[source,java,indent=0]
.{examplesdir}/uds/Application.java
----
include::{examplesdir}/uds/Application.java[lines=18..33]
----
<1> Specifies `DomainSocketAddress` that will be used
====
== Host Name Resolution
By default, the `HttpClient` uses Netty's domain name lookup mechanism that resolves a domain name asynchronously.
This is as an alternative of the JVM's built-in blocking resolver.

When you need to change the default settings, you can configure the `HttpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/resolver/Application.java
----
include::{examplesdir}/resolver/Application.java[lines=18..39]
----
<1> The timeout of each DNS query performed by this resolver will be 500ms.
====

The following listing shows the available configurations:

[width="100%",options="header"]
|=======
| Configuration name | Description
| `cacheMaxTimeToLive` | The max time to live of the cached DNS resource records (resolution: seconds).
If the time to live of the DNS resource record returned by the DNS server is greater
than this max time to live, this resolver ignores the time to live from
the DNS server and uses this max time to live.
Default to `Integer.MAX_VALUE`.
| `cacheMinTimeToLive` | The min time to live of the cached DNS resource records (resolution: seconds).
If the time to live of the DNS resource record returned by the DNS server is less
than this min time to live, this resolver ignores the time to live from
the DNS server and uses this min time to live.
Default: 0.
| `cacheNegativeTimeToLive` | The time to live of the cache for the failed DNS queries (resolution: seconds). Default: 0.
| `disableOptionalRecord` | Disables the automatic inclusion of an optional record that tries to give a hint to the remote DNS server about
how much data the resolver can read per response. By default, this setting is enabled.
| `disableRecursionDesired` | Specifies whether this resolver has to send a DNS query with the recursion desired (RD) flag set.
By default, this setting is enabled.
| `maxPayloadSize` | Sets the capacity of the datagram packet buffer (in bytes). Default: 4096.
| `maxQueriesPerResolve` | Sets the maximum allowed number of DNS queries to send when resolving a host name. Default: 16.
| `ndots` | Sets the number of dots that must appear in a name before an initial absolute query is made.
Default: -1 (to determine the value from the OS on Unix or use a value of 1 otherwise).
| `queryTimeout` | Sets the timeout of each DNS query performed by this resolver (resolution: milliseconds). Default: 5000.
| `resolvedAddressTypes` | The list of the protocol families of the resolved address.
| `roundRobinSelection` | Enables an
{nettyjavadoc}/io/netty/resolver/AddressResolverGroup.html[`AddressResolverGroup`] of
{nettyjavadoc}/io/netty/resolver/dns/DnsNameResolver.html[`DnsNameResolver`] that supports random selection
of destination addresses if multiple are provided by the nameserver.
See {nettyjavadoc}/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroup.html[`RoundRobinDnsAddressResolverGroup`].
Default: {nettyjavadoc}/io/netty/resolver/dns/DnsAddressResolverGroup.html[`DnsAddressResolverGroup`]
| `runOn` | Performs the communication with the DNS servers on the given
{javadoc}/reactor/netty/resources/LoopResources.html[`LoopResources`]. By default, the LoopResources
specified on the client level are used.
| `searchDomains` | The list of search domains of the resolver.
By default, the effective search domain list is populated by using the system DNS search domains.
| `trace` | A specific logger and log level to be used by this resolver when generating detailed trace
information in case of resolution failure.
|=======

Sometimes, you may want to switch to the JVM built-in resolver. To do so, you can configure the `HttpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/resolver/custom/Application.java
----
include::{examplesdir}/resolver/custom/Application.java[lines=18..38]
----
<1> Sets the JVM built-in resolver.
====
