:sourcedir: ./../../reactor-netty-http/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server
:javadoc: https://projectreactor.io/docs/netty/release/api

[[http-server]]
= HTTP Server

`Reactor Netty` provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/http/server/HttpServer.html[`HttpServer`] class.
It hides most of the `Netty` functionality that is needed in order to create a `HTTP` server
and adds `Reactive Streams` backpressure.

== Starting and Stopping

To start an HTTP server, you must create and configure a
{javadoc}/reactor/netty/http/server/HttpServer.html[HttpServer] instance.
By default, the `host` is configured for any local address, and the system picks up an ephemeral port
when the `bind` operation is invoked.
The following example shows how to create an `HttpServer` instance:

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..31]
----
<1> Creates an {javadoc}/reactor/netty/http/server/HttpServer.html[HttpServer]
instance ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/DisposableServer.html[`DisposableServer`]
offers a simple server API, including {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the server down in a blocking fashion.

=== Host and Port

To serve on a specific `host` and `port`, you can apply the following configuration to the `HTTP` server:

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..33]
----
<1> Configures the `HTTP` server host
<2> Configures the `HTTP` server port
====

== Eager Initialization

By default, the initialization of the `HttpServer` resources happens on demand. This means that the `bind
operation` absorbs the extra time needed to initialize and load:

 * the event loop groups
 * the native transport libraries (when native transport is used)
 * the native libraries for the security (in case of `OpenSsl`)

When you need to preload these resources, you can configure the `HttpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/warmup/Application.java
----
include::{examplesdir}/warmup/Application.java[lines=18..36]
----
<1> Initialize and load the event loop groups, the native transport libraries and the native libraries for the security
====

== Routing HTTP

Defining routes for the `HTTP` server requires configuring the provided
{javadoc}/reactor/netty/http/server/HttpServerRoutes.html[`HttpServerRoutes`] builder.
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/routing/Application.java
----
include::{examplesdir}/routing/Application.java[lines=18..41]
----
<1> Serves a `GET` request to `/hello` and returns `Hello World!`
<2> Serves a `POST` request to `/echo` and returns the received request body as a response.
<3> Serves a `GET` request to `/path/{param}` and returns the value of the path parameter.
<4> Serves websocket to `/ws` and returns the received incoming data as outgoing data.
====

NOTE: The server routes are unique and only the first matching in order of declaration is invoked.

=== SSE

The following code shows how you can configure the `HTTP` server to serve `Server-Sent Events`:

====
[source,java,indent=0]
.{examplesdir}/sse/Application.java
----
include::{examplesdir}/sse/Application.java[lines=18..76]
----
====

=== Static Resources

The following code shows how you can configure the `HTTP` server to serve static resources:

====
[source,java,indent=0]
.{examplesdir}/staticresources/Application.java
----
include::{examplesdir}/staticresources/Application.java[lines=18..37]
----
====

== Writing Data

To send data to a connected client, you must attach an I/O handler by using either
{javadoc}/reactor/netty/http/server/HttpServer.html#handle-java.util.function.BiFunction-[`handle(...)`] or
{javadoc}/reactor/netty/http/server/HttpServer.html#route-java.util.function.Consumer-[`route(...)`].
The I/O handler has access to {javadoc}/reactor/netty/http/server/HttpServerResponse.html[`HttpServerResponse`],
to be able to write data. The following example uses the `handle(...)` method:

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..33]
----
<1> Sends `hello` string to the connected clients
====

=== Adding Headers and Other Metadata

When you send data to the connected clients, you may need to send additional headers,
cookies, status code, and other metadata.
You can provide this additional metadata by using
{javadoc}/reactor/netty/http/server/HttpServerResponse.html[`HttpServerResponse`].
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/send/headers/Application.java
----
include::{examplesdir}/send/headers/Application.java[lines=18..40]
----
====

=== Compression

You can configure the `HTTP` server to send a compressed response, depending on the request header
`Accept-Encoding`.

`Reactor Netty` provides three different strategies for compressing the outgoing data:

* `compress(boolean)`: Depending on the boolean that is provided, the compression is enabled (`true`) or disabled (`false`).
* `compress(int)`: The compression is performed once the response size exceeds the given value (in bytes).
* `compress(BiPredicate<HttpServerRequest, HttpServerResponse>)`: The compression is performed if
the predicate returns `true`.

The following example uses the `compress` method (set to `true`) to enable compression:

====
[source,java,indent=0]
.{examplesdir}/compression/Application.java
----
include::{examplesdir}/compression/Application.java[lines=18..38]
----
====

== Consuming Data

To receive data from a connected client, you must attach an I/O handler by using either
{javadoc}/reactor/netty/http/server/HttpServer.html#handle-java.util.function.BiFunction-[`handle(...)`] or
{javadoc}/reactor/netty/http/server/HttpServer.html#route-java.util.function.Consumer-[`route(...)`].
The I/O handler has access to {javadoc}/reactor/netty/http/server/HttpServerRequest.html[`HttpServerRequest`],
to be able to read data.

The following example uses the `handle(...)` method:

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..32]
----
<1> Receives data from the connected clients
====

=== Reading Headers, URI Params, and other Metadata

When you receive data from the connected clients, you might need to check request headers,
parameters, and other metadata. You can obtain this additional metadata by using
{javadoc}/reactor/netty/http/server/HttpServerRequest.html[`HttpServerRequest`].
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/read/headers/Application.java
----
include::{examplesdir}/read/headers/Application.java[lines=18..40]
----
====

==== Obtaining the Remote (Client) Address

In addition to the metadata that you can obtain from the request, you can also receive the
`host (server)` address, the `remote (client)` address and the `scheme`. Depending on the
chosen factory method, you can retrieve the information directly from the channel or by
using the `Forwarded` or `X-Forwarded-*` `HTTP` request headers.
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/clientaddress/Application.java
----
include::{examplesdir}/clientaddress/Application.java[lines=18..38]
----
<1> Specifies that the information about the connection is to be obtained from the `Forwarded` and `X-Forwarded-*`
`HTTP` request headers, if possible.
<2> Returns the address of the remote (client) peer.
====

It is also possible to customize the behavior of the `Forwarded` or `X-Forwarded-*` header handler.
The following example shows how to do so:

====
[source,java,indent=0]
.{examplesdir}/clientaddress/CustomForwardedHeaderHandlerApplication.java
----
include::{examplesdir}/clientaddress/CustomForwardedHeaderHandlerApplication.java[lines=18..52]
----
<1> Add a custom header handler.
<2> Returns the address of the remote (client) peer.
====

=== HTTP Request Decoder

By default, `Netty` configures some restrictions for the incoming requests, such as:

* The maximum length of the initial line.
* The maximum length of all headers.
* The maximum length of the content or each chunk.

For more information, see https://netty.io/4.1/api/io/netty/handler/codec/http/HttpRequestDecoder.html[`HttpRequestDecoder`]
and https://netty.io/4.1/api/io/netty/handler/codec/http/HttpServerUpgradeHandler.html[`HttpServerUpgradeHandler`]

By default, the `HTTP` server is configured with the following settings:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/HttpDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/HttpDecoderSpec.java[lines=29..33]
----
====
====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/server/HttpRequestDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/server/HttpRequestDecoderSpec.java[lines=34..39]
----
====

When you need to change these default settings, you can configure the `HTTP` server as follows:

====
[source,java,indent=0]
.{examplesdir}/requestdecoder/Application.java
----
include::{examplesdir}/requestdecoder/Application.java[lines=18..34]
----
<1> The maximum length of all headers will be `16384`.
When this value is exceeded, a
https://netty.io/4.1/api/io/netty/handler/codec/TooLongFrameException.html[TooLongFrameException]
is raised.
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `HttpServer`:

[width="100%",options="header"]
|=======
| Callback | Description
| `doOnBind` | Invoked when the server channel is about to bind.
| `doOnBound` | Invoked when the server channel is bound.
| `doOnChannelInit` | Invoked when initializing the channel.
| `doOnConnection` | Invoked when a remote client is connected
| `doOnUnbound` | Invoked when the server channel is unbound.
|=======

The following example uses the `doOnConnection` and `doOnChannelInit` callbacks:

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..39]
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when a remote client is connected.
<2> `Netty` pipeline is extended with `LoggingHandler` when initializing the channel.
====

== TCP-level Configuration

When you need to change configuration on the TCP level, you can use the following snippet
to extend the default `TCP` server configuration:

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..33]
----
====

See <<tcp-server>> for more detail about TCP-level configuration.

=== Wire Logger

`Reactor Netty` provides wire logging for when you need to inspect the traffic between the peers.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.http.server.HttpServer` level to `DEBUG`
and apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..32]
----
<1> Enables the wire logging
====

By default, the wire logging uses {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#HEX_DUMP[AdvancedByteBufFormat#HEX_DUMP]
when printing the content.
When you need to change this to {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#SIMPLE[AdvancedByteBufFormat#SIMPLE]
or {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL],
you can configure the `HttpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/wiretap/custom/Application.java
----
include::{examplesdir}/wiretap/custom/Application.java[lines=18..34]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL] is used for
printing the content.
====

== SSL and TLS

When you need SSL or TLS, you can apply the configuration shown in the next example.
By default, if `OpenSSL` is available,
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
provider is used as a provider. Otherwise
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[`SslProvider.JDK`] is used.
You can switch the provider by using
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.

The following example uses `SslContextBuilder`:

====
[source,java,indent=0]
.{examplesdir}/security/Application.java
----
include::{examplesdir}/security/Application.java[lines=18..39]
----
====

=== Server Name Indication
You can configure the `HTTP` server with multiple `SslContext` mapped to a specific domain.
An exact domain name or a domain name containing a wildcard can be used when configuring the `SNI` mapping.

The following example uses a domain name containing a wildcard:

====
[source,java,indent=0]
.{examplesdir}/sni/Application.java
----
include::{examplesdir}/sni/Application.java[lines=18..47]
----
====

== HTTP Access Log

You can enable the `HTTP` access log either programmatically or by configuration. By default, it is disabled.

You can use `-Dreactor.netty.http.server.accessLogEnabled=true` to enable the `HTTP` access log by configuration.

You can use the following configuration (for Logback or similar logging frameworks) to have a separate
`HTTP` access log file:

====
[source,xml]
----
<appender name="accessLog" class="ch.qos.logback.core.FileAppender">
    <file>access_log.log</file>
    <encoder>
        <pattern>%msg%n</pattern>
    </encoder>
</appender>
<appender name="async" class="ch.qos.logback.classic.AsyncAppender">
    <appender-ref ref="accessLog" />
</appender>

<logger name="reactor.netty.http.server.AccessLog" level="INFO" additivity="false">
    <appender-ref ref="async"/>
</logger>
----
====

The following example enables it programmatically:
====
[source,java,indent=0]
.{examplesdir}/accessLog/Application.java
----
include::{examplesdir}/accessLog/Application.java[lines=18..32]
----
====

Calling this method takes precedence over the system property configuration.

By default, the logging format is https://en.wikipedia.org/wiki/Common_Log_Format[Common Log Format], but you can
specify a custom one as a parameter, as in the following example:
====
[source,java,indent=0]
.{examplesdir}/accessLog/CustomLogAccessFormatApplication.java
----
include::{examplesdir}/accessLog/CustomLogAccessFormatApplication.java[lines=18..33]
----
====

You can also filter `HTTP` access logs by using the `AccessLogFactory#createFilter` method, as in the following example:
====
[source,java,indent=0]
.{examplesdir}/accessLog/FilterLogAccessApplication.java
----
include::{examplesdir}/accessLog/FilterLogAccessApplication.java[lines=18..34]
----
====

Note that this method can take a custom format parameter too, as in this example:
====
[source,java,indent=0]
.{examplesdir}/accessLog/CustomFormatAndFilterAccessLogApplication.java.java
----
include::{examplesdir}/accessLog/CustomFormatAndFilterAccessLogApplication.java[lines=18..35]
----
<1> Specifies the filter predicate to use
<2> Specifies the custom format to apply

====

== HTTP/2

By default, the `HTTP` server supports `HTTP/1.1`. If you need `HTTP/2`, you can get it through configuration.
In addition to the protocol configuration, if you need `H2` but not `H2C (cleartext)`, you must also configure SSL.

NOTE: As Application-Layer Protocol Negotiation (ALPN) is not supported "`out-of-the-box`" by JDK8 (although some vendors backported ALPN to JDK8), you need an additional dependency to a native library that
supports it -- for example, https://netty.io/wiki/forked-tomcat-native.html[`netty-tcnative-boringssl-static`].

The following listing presents a simple `H2` example:

====
[source,java,indent=0]
.{examplesdir}/http2/H2Application.java
----
include::{examplesdir}/http2/H2Application.java[lines=18..44]
----
<1> Configures the server to support only `HTTP/2`
<2> Configures `SSL`
====

The application should now behave as follows:

====
[source,bash]
----
$ curl --http2 https://localhost:8080 -i
HTTP/2 200

hello
----
====

The following listing presents a simple `H2C` example:

====
[source,java,indent=0]
.{examplesdir}/http2/H2CApplication.java
----
include::{examplesdir}/http2/H2CApplication.java[lines=18..41]
----
====

The application should now behave as follows:

====
[source,bash]
----
$ curl --http2-prior-knowledge http://localhost:8080 -i
HTTP/2 200

hello
----
====

=== Protocol Selection

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/http/HttpProtocol.java
----
include::{sourcedir}/reactor/netty/http/HttpProtocol.java[lines=24..52]
----
====

== Metrics
The HTTP server supports built-in integration with https://micrometer.io/[`Micrometer`].
It exposes all metrics with a prefix of `reactor.netty.http.server`.

The following table provides information for the HTTP server metrics:

[width="100%",options="header"]
|=======
| metric name | type | description
| reactor.netty.http.server.data.received | DistributionSummary | Amount of the data received, in bytes
| reactor.netty.http.server.data.sent | DistributionSummary | Amount of the data sent, in bytes
| reactor.netty.http.server.errors | Counter | Number of errors that occurred
| reactor.netty.http.server.data.received.time | Timer | Time spent in consuming incoming data
| reactor.netty.http.server.data.sent.time | Timer | Time spent in sending outgoing data
| reactor.netty.http.server.response.time | Timer | Total time for the request/response
|=======

These additional metrics are also available:

include::alloc-metrics.adoc[]

The following example enables that integration:

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..52]
----
<1> Applies upper limit for the meters with `URI` tag
<2> Templated URIs will be used as an URI tag value when possible
<3> Enables the built-in integration with Micrometer
====

NOTE: In order to avoid a memory and CPU overhead of the enabled metrics, it is important to convert the real URIs to templated URIs when possible.
Without a conversion to a template-like form, each distinct URI leads to the creation of a distinct tag, which takes a lot of memory for the metrics.

NOTE: Always apply an upper limit for the meters with URI tags. Configuring an upper limit on the number of meters can help in cases when the real URIs cannot be templated.
You can find more information at https://micrometer.io/docs/concepts#_denyaccept_meters[`maximumAllowableTags`].

When HTTP server metrics are needed for an integration with a system other than `Micrometer` or you want
to provide your own integration with `Micrometer`, you can provide your own metrics recorder, as follows:

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..41]
----
<1> Enables HTTP server metrics and provides {javadoc}/reactor/netty/http/server/HttpServerMetricsRecorder.html[`HttpServerMetricsRecorder`] implementation.
====

== Unix Domain Sockets
The `HTTP` server supports Unix Domain Sockets (UDS) when native transport is in use.

The following example shows how to use UDS support:

====
[source,java,indent=0]
.{examplesdir}/uds/Application.java
----
include::{examplesdir}/uds/Application.java[lines=18..33]
----
<1> Specifies `DomainSocketAddress` that will be used
====
