:sourcedir: ./../../reactor-netty-core/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-server]]
= TCP Server

`Reactor Netty` provides an easy to use and configure
{javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`].
It hides most of the `Netty` functionality that is needed to create a `TCP` server
and adds `Reactive Streams` backpressure.

== Starting and Stopping

To start a `TCP` server, you must create and configure a
{javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`] instance.
By default, the `host` is configured for any local address, and the system picks up an ephemeral port
when the `bind` operation is invoked. The following example shows how to create and
configure a `TcpServer` instance:

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..31]
----
<1> Creates a {javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`]
instance that is ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/DisposableServer.html[`DisposableServer`]
offers a simple server API, including {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the server down in a blocking fashion.

=== Host and Port

To serve on a specific `host` and `port`, you can apply the following configuration to the `TCP` server:

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..33]
----
<1> Configures the `TCP` server host
<2> Configures the `TCP` server port
====

== Eager Initialization

By default, the initialization of the `TcpServer` resources happens on demand. This means that the `bind
operation` absorbs the extra time needed to initialize and load:

 * the event loop groups
 * the native transport libraries (when native transport is used)
 * the native libraries for the security (in case of `OpenSsl`)

When you need to preload these resources, you can configure the `TcpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/warmup/Application.java
----
include::{examplesdir}/warmup/Application.java[lines=18..36]
----
<1> Initialize and load the event loop groups, the native transport libraries and the native libraries for the security
====

== Writing Data

In order to send data to a connected client, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyOutbound.html[`NettyOutbound`]
to be able to write data. The following example shows how to attach an I/O handler:

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..33]
----
<1> Sends `hello` string to the connected clients
====

== Consuming Data

In order to receive data from a connected client, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyInbound.html[`NettyInbound`]
to be able to read data. The following example shows how to use it:

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..32]
----
<1> Receives data from the connected clients
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `TcpServer`:

[width="100%",options="header"]
|=======
| Callback | Description
| `doOnBind` | Invoked when the server channel is about to bind.
| `doOnBound` | Invoked when the server channel is bound.
| `doOnChannelInit` | Invoked when initializing the channel.
| `doOnConnection` | Invoked when a remote client is connected
| `doOnUnbound` | Invoked when the server channel is unbound.
|=======

The following example uses the `doOnConnection` and `doOnChannelInit` callbacks:

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..39]
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when a remote client is connected.
<2> `Netty` pipeline is extended with `LoggingHandler` when initializing the channel.
====

== TCP-level Configurations

This section describes three kinds of configuration that you can use at the TCP level:

* <<server-tcp-level-configurations-channel-options>>
* <<server-tcp-level-configurations-event-wire-logger>>
* <<server-tcp-level-configurations-event-loop-group>>

[[server-tcp-level-configurations-channel-options]]
=== Setting Channel Options

By default, the `TCP` server is configured with the following options:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/tcp/TcpServerBind.java
----
include::{sourcedir}/reactor/netty/tcp/TcpServerBind.java[lines=40..48]
----
====

If additional options are necessary or changes to the current options are needed, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..33]
----
====

You can find more about `Netty` channel options at the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[server-tcp-level-configurations-event-wire-logger]]
=== Using a Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.tcp.TcpServer` level to `DEBUG`
and apply the following configuration;

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..32]
----
<1> Enables the wire logging
====

By default, the wire logging uses {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#HEX_DUMP[AdvancedByteBufFormat#HEX_DUMP]
when printing the content.
When you need to change this to {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#SIMPLE[AdvancedByteBufFormat#SIMPLE]
or {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL],
you can configure the `TcpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/wiretap/custom/Application.java
----
include::{examplesdir}/wiretap/custom/Application.java[lines=18..34]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL] is used for
printing the content.
====

[[server-tcp-level-configurations-event-loop-group]]
=== Using an Event Loop Group

By default, the `TCP` server uses an "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods.

The default configuration for the `Event Loop Group` is the following:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=84..113]
----
====

If changes to the these settings are needed, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/eventloop/Application.java
----
include::{examplesdir}/eventloop/Application.java[lines=18..35]
----
====

== SSL and TLS

When you need SSL or TLS, you can apply the configuration shown in the next listing.
By default, if `OpenSSL` is available,
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
provider is used as a provider. Otherwise
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[`SslProvider.JDK`] is used.
Switching the provider can be done through
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.

The following example uses `SslContextBuilder`:

====
[source,java,indent=0]
.{examplesdir}/security/Application.java
----
include::{examplesdir}/security/Application.java[lines=18..39]
----
====

=== Server Name Indication
You can configure the `TCP` server with multiple `SslContext` mapped to a specific domain.
An exact domain name or a domain name containing a wildcard can be used when configuring the `SNI` mapping.

The following example uses a domain name containing a wildcard:

====
[source,java,indent=0]
.{examplesdir}/sni/Application.java
----
include::{examplesdir}/sni/Application.java[lines=18..47]
----
====

== Metrics
The TCP server supports built-in integration with https://micrometer.io/[`Micrometer`].
It exposes all metrics with a prefix of `reactor.netty.tcp.server`.

The following table provides information for the TCP server metrics:

[width="100%",options="header"]
|=======
| metric name | type | description
| reactor.netty.tcp.server.data.received | DistributionSummary | Amount of the data received, in bytes
| reactor.netty.tcp.server.data.sent | DistributionSummary | Amount of the data sent, in bytes
| reactor.netty.tcp.server.errors | Counter | Number of errors that occurred
| reactor.netty.tcp.server.tls.handshake.time | Timer | Time spent for TLS handshake
|=======

These additional metrics are also available:

include::alloc-metrics.adoc[]

The following example enables that integration:

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..32]
----
<1> Enables the built-in integration with Micrometer
====

When TCP server metrics are needed for an integration with a system other than `Micrometer` or you want
to provide your own integration with `Micrometer`, you can provide your own metrics recorder, as follows:

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..35]
----
<1> Enables TCP server metrics and provides {javadoc}/reactor/netty/channel/ChannelMetricsRecorder.html[`ChannelMetricsRecorder`] implementation.
====

== Unix Domain Sockets
The `TCP` server supports Unix Domain Sockets (UDS) when native transport is in use.

The following example shows how to use UDS support:

====
[source,java,indent=0]
.{examplesdir}/uds/Application.java
----
include::{examplesdir}/uds/Application.java[lines=18..33]
----
<1> Specifies `DomainSocketAddress` that will be used
====
