:sourcedir: ./../../reactor-netty-core/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client
:javadoc: https://projectreactor.io/docs/netty/release/api

[[udp-client]]
= UDP Client

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`].
It hides most of the Netty functionality that is required to create a `UDP` client
and adds Reactive Streams backpressure.

== Connecting and Disconnecting

To connect the UDP client to a given endpoint, you must create and configure a
{javadoc}/reactor/netty/udp/UdpClient.html[UdpClient] instance.
By default, the host is configured for `localhost` and the port is `12012`.
The following example shows how to create and connect a UDP client:

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..32]
----
<1> Creates a {javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`]
instance that is ready for configuring.
<2> Connects the client in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/Connection.html[`Connection`]
offers a simple connection API, including {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the client down in a blocking fashion.

=== Host and Port

To connect to a specific `host` and `port`, you can apply the following configuration to the `UDP` client:

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..34]
----
<1> Configures the `host` to which this client should connect
<2> Configures the `port` to which this client should connect
====

== Eager Initialization

By default, the initialization of the `UdpClient` resources happens on demand. This means that the `connect
operation` absorbs the extra time needed to initialize and load:

 * the event loop group
 * the host name resolver
 * the native transport libraries (when native transport is used)

When you need to preload these resources, you can configure the `UdpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/warmup/Application.java
----
include::{examplesdir}/warmup/Application.java[lines=18..40]
----
<1> Initialize and load the event loop group, the host name resolver, and the native transport libraries
<2> Host name resolution happens when connecting to the remote peer
====

== Writing Data

To send data to a given peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpOutbound.html[`UdpOutbound`],
to be able to write data.

The following example shows how to send `hello`:

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..37]
----
<1> Sends `hello` string to the remote peer.
====

== Consuming Data

To receive data from a given peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpInbound.html[`UdpInbound`],
to be able to read data.
The following example shows how to consume data:

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..35]
----
<1> Receives data from a given peer
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `UdpClient`:

[width="100%",options="header"]
|=======
| Callback | Description
| `doAfterResolve` | Invoked after the remote address has been resolved successfully.
| `doOnChannelInit` | Invoked when initializing the channel.
| `doOnConnect` | Invoked when the channel is about to connect.
| `doOnConnected` | Invoked after the channel has been connected.
| `doOnDisconnected` | Invoked after the channel has been disconnected.
| `doOnResolve` | Invoked when the remote address is about to be resolved.
| `doOnResolveError` | Invoked in case the remote address hasn't been resolved successfully.
|=======

The following example uses the `doOnConnected` and `doOnChannelInit` callbacks:

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..40]
----
<1> `Netty` pipeline is extended with `LineBasedFrameDecoder` when the channel has been connected.
<2> `Netty` pipeline is extended with `LoggingHandler` when initializing the channel.
====

== Connection Configuration

This section describes three kinds of configuration that you can use at the UDP level:

* <<client-udp-connection-configurations-channel-options>>
* <<client-udp-connection-configurations-wire-logger>>
* <<client-udp-connection-configurations-event-loop-group>>

[[client-udp-connection-configurations-channel-options]]
=== Channel Options

By default, the `UDP` client is configured with the following options:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/udp/UdpClientConnect.java
----
include::{sourcedir}/reactor/netty/udp/UdpClientConnect.java[lines=37..42]
----
====

If you need additional options or need to change the current options, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..36]
----
====

You can find more about Netty channel options at the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[client-udp-connection-configurations-wire-logger]]
=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.udp.UdpClient` level to `DEBUG`
and apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..35]
----
<1> Enables the wire logging
====

By default, the wire logging uses {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#HEX_DUMP[AdvancedByteBufFormat#HEX_DUMP]
when printing the content.
When you need to change this to {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#SIMPLE[AdvancedByteBufFormat#SIMPLE]
or {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL],
you can configure the `UdpClient` as follows:

====
[source,java,indent=0]
.{examplesdir}/wiretap/custom/Application.java
----
include::{examplesdir}/wiretap/custom/Application.java[lines=18..34]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL] is used for
printing the content.
====

[[client-udp-connection-configurations-event-loop-group]]
=== Event Loop Group

By default, the UDP client uses "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[`LoopResources`]`#create`
methods.

The following listing shows the default configuration for the "`Event Loop Group`":

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=84..113]
----
====

If you need changes to the these settings, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/eventloop/Application.java
----
include::{examplesdir}/eventloop/Application.java[lines=18..38]
----
====

== Metrics
The UDP client supports built-in integration with https://micrometer.io/[`Micrometer`].
It exposes all metrics with a prefix of `reactor.netty.udp.client`.

The following table provides information for the UDP client metrics:

[width="100%",options="header"]
|=======
| metric name | type | description
| reactor.netty.udp.client.data.received | DistributionSummary | Amount of the data received, in bytes
| reactor.netty.udp.client.data.sent | DistributionSummary | Amount of the data sent, in bytes
| reactor.netty.udp.client.errors | Counter | Number of errors that occurred
| reactor.netty.udp.client.connect.time | Timer | Time spent for connecting to the remote address
| reactor.netty.udp.client.address.resolver | Timer | Time spent for resolving the address
|=======

These additional metrics are also available:

include::alloc-metrics.adoc[]

The following example enables that integration:

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..36]
----
<1> Enables the built-in integration with Micrometer
====

When UDP client metrics are needed for an integration with a system other than `Micrometer` or you want
to provide your own integration with `Micrometer`, you can provide your own metrics recorder, as follows:

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..37]
----
<1> Enables UDP client metrics and provides {javadoc}/reactor/netty/channel/ChannelMetricsRecorder.html[`ChannelMetricsRecorder`] implementation.
====
