:sourcedir: ./../../reactor-netty-core/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server
:javadoc: https://projectreactor.io/docs/netty/release/api

[[udp-server]]
= UDP Server

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/udp/UdpServer.html[`UdpServer`].
It hides most of the Netty functionality that is required to create a `UDP` server
and adds `Reactive Streams` backpressure.

== Starting and Stopping

To start a UDP server, a {javadoc}/reactor/netty/udp/UdpServer.html[UdpServer]
instance has to be created and configured.
By default, the host is configured to be `localhost` and the port is `12012`.
The following example shows how to create and start a UDP server:

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..32]
----
<1> Creates a {javadoc}/reactor/netty/udp/UdpServer.html[`UdpServer`]
instance that is ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/Connection.html[`Connection`]
offers a simple server API, including {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the server down in a blocking fashion.

=== Host and Port

In order to serve on a specific host and port, you can apply the following configuration to the `UDP` server:

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..34]
----
<1> Configures the `UDP` server host
<2> Configures the `UDP` server port
====

== Eager Initialization

By default, the initialization of the `UdpServer` resources happens on demand. This means that the `bind
operation` absorbs the extra time needed to initialize and load:

 * the event loop group
 * the native transport libraries (when native transport is used)

When you need to preload these resources, you can configure the `UdpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/warmup/Application.java
----
include::{examplesdir}/warmup/Application.java[lines=18..51]
----
<1> Initialize and load the event loop group and the native transport libraries
====

== Writing Data

To send data to the remote peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpOutbound.html[`UdpOutbound`],
to be able to write data.
The following example shows how to send `hello`:

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..51]
----
<1> Sends a `hello` string to the remote peer
====

== Consuming Data

To receive data from a remote peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpInbound.html[`UdpInbound`],
to be able to read data.
The following example shows how to consume data:

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..47]
----
<1> Receives data from the remote peer
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `UdpServer`:

[width="100%",options="header"]
|=======
| Callback | Description
| `doOnBind` | Invoked when the server channel is about to bind.
| `doOnBound` | Invoked when the server channel is bound.
| `doOnChannelInit` | Invoked when initializing the channel.
| `doOnUnbound` | Invoked when the server channel is unbound.
|=======

The following example uses the `doOnBound` and `doOnChannelInit` callbacks:

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..39]
----
<1> `Netty` pipeline is extended with `LineBasedFrameDecoder` when the server channel is bound.
<2> `Netty` pipeline is extended with `LoggingHandler` when initializing the channel.
====

== Connection Configuration

This section describes three kinds of configuration that you can use at the UDP level:

* <<server-udp-connection-configurations-channel-options>>
* <<server-udp-connection-configurations-wire-logger>>
* <<server-udp-connection-configurations-event-loop-group>>

[[server-udp-connection-configurations-channel-options]]
=== Channel Options

By default, the `UDP` server is configured with the following options:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/udp/UdpServerBind.java
----
include::{sourcedir}/reactor/netty/udp/UdpServerBind.java[lines=40..44]
----
====

If you need additional options or need to change the current options, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..34]
----
====

For more information about Netty channel options, see the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[server-udp-connection-configurations-wire-logger]]
=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.udp.UdpServer` level to `DEBUG`
and apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..33]
----
<1> Enables the wire logging
====

By default, the wire logging uses {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#HEX_DUMP[AdvancedByteBufFormat#HEX_DUMP]
when printing the content.
When you need to change this to {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#SIMPLE[AdvancedByteBufFormat#SIMPLE]
or {javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL],
you can configure the `UdpServer` as follows:

====
[source,java,indent=0]
.{examplesdir}/wiretap/custom/Application.java
----
include::{examplesdir}/wiretap/custom/Application.java[lines=18..34]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty/transport/logging/AdvancedByteBufFormat.html#TEXTUAL[AdvancedByteBufFormat#TEXTUAL] is used for
printing the content.
====

[[server-udp-connection-configurations-event-loop-group]]
=== Event Loop Group

By default, the UDP server uses "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods.

The default configuration for the "`Event Loop Group`" is the following:

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=84..113]
----
====

If you need changes to these settings, you can apply the following configuration:

====
[source,java,indent=0]
.{examplesdir}/eventloop/Application.java
----
include::{examplesdir}/eventloop/Application.java[lines=18..36]
----
====

== Metrics
The UDP server supports built-in integration with https://micrometer.io/[`Micrometer`].
It exposes all metrics with a prefix of `reactor.netty.udp.server`.

The following table provides information for the UDP server metrics:

[width="100%",options="header"]
|=======
| metric name | type | description
| reactor.netty.udp.server.data.received | DistributionSummary | Amount of the data received, in bytes
| reactor.netty.udp.server.data.sent | DistributionSummary | Amount of the data sent, in bytes
| reactor.netty.udp.server.errors | Counter | Number of errors that occurred
|=======

These additional metrics are also available:

include::alloc-metrics.adoc[]

The following example enables that integration:

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..34]
----
<1> Enables the built-in integration with Micrometer
====

When UDP server metrics are needed for an integration with a system other than `Micrometer` or you want
to provide your own integration with `Micrometer`, you can provide your own metrics recorder, as follows:

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..35]
----
<1> Enables UDP server metrics and provides {javadoc}/reactor/netty/channel/ChannelMetricsRecorder.html[`ChannelMetricsRecorder`] implementation.
====
