== Reactive Streams over Aeron

For more information regarding Aeron go to https://github.com/real-logic/Aeron[Aeron Project Home]

Support of http://www.reactive-streams.org/[Reactive Streams] over Aeron transport introduced in module reactor-aeron.

.Core reactor-aeron classes and their purpose
[cols="m,d", options="header"]
|============================
| Class          | Purpose
| Context        | Provides configuration parameters for AeronSubscriber, AeronPublisher and AeronProcessor
| AeronSubscriber| Plays a role of a server. Passes signals to clients over Aeron.
| AeronPublisher | Plays a role of a client. Receives signals from the server.
| AeronProcessor | Plays both roles of a server and a client.
|============================

=== Quick start

.Starting a server on box serverbox in unicast mode on UDP port 12000:
[source,java]
----
AeronSubscriber subscriber = AeronSubscriber.create(new Context()
    .senderChannel("udp://serverbox:12000"));
----

.Starting a client to be run on box clientbox on UDP port 12001 and connecting to the server on serverbox above:
[source,java]
----
AeronPublisher publisher = AeronPublisher.create(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://clientbox:12001"));
----

=== Embedded Aeron Media driver

By default AeronSubscriber, AeronPublisher and AeronProcessor launch embedded Aeron Media Driver if it wasn't launched
previously. Only a single instance of the embedded `MediaDriver` is normally supported per JVM.
Also a single `Aeron` instance is supported when the embedded media driver is used.

If you need to use your own Aeron instance then it needs to be set into `Context.aeron` field.

You can adjust embedded media driver configuration `MediaDriver.Context` via
`EmbeddedMediaDriverManager.getInstance().getDriverContext()`
before the driver is started.

The embedded Media driver shutdown specifics and clean up activity can be set up via fields of
`EmbeddedMediaDriverManager` instance.

=== AeronSubscriber as server

AeronSubscriber plays a role of a server which passes signals from an upstream publisher to receivers via Aeron.

The subscriber is configured via fields of `Context' which have default values and normally there is no need
to adjust them.

.Most important fields of `Context` for `AeronSubscriber`
[cols="m,d", options="header"]
|======================================================
| Field                   | Description
| errorConsumer           | Consumer of errors encountered
| publicationRetryMillis  | Number of milliseconds to wait before giving up publishing of a message into Aeron. +
When publication fails the corresponding exception is reported into `errorConsumer`.
| heartbeatIntervalMillis | Interval in milliseconds for sending heartbeats from a signal receiver to a signal sender. +
Is used on the sender side to clean up dead receivers. +
A receiver is considered dead if not heartbeat was received from it during `heartbeatIntervalMillis` * 1.5 milliseconds.
| multicastUpstreamRequest| Number of signals requested from an upstream publisher in a single call to its subscription
by multicast sender.
| senderChannel           | Aeron channel on which to listen for inbound requests from clients. +
|======================================================

`senderChannel` has the following format: `udp://<Network Interface IP Address>|<hostname>:<Port>` +
Where `Network Interface IP Address` is the IP address of a network interface used for sending signals. +
Alternatively hostname on the network could be provided as it's resolved to the corresponding network interface IP.

In version 2.5 the functionality uses 3 Aeron streams with ids specified below and having default values.
.Aeron stream Ids used for communication between AeronSubscriber and AeronPublisher
[cols="m,d", options="header"]
|=========================================
| streamId                       | Purpose
| Context.streamId               | To communicate Next and Complete signals from a server to a client
| Context.errorStreamId          | To communicate Error signals from a server to a client
| Context.serviceRequestStreamId | To communicate `.cancel()` and `.request(N)` actions from a client to a server
|=========================================

Normally there is no need to modify values of streamIds used unless you need to run several instances of AeronSubscriber
on the same channel.

==== Unicast sending mode

The communication between `AeronSubscriber` and `AeronPublisher` can be done via both unicast and multicast UDP.

To configure AeronSubscriber in unicast mode leave field 'Context.senderChannel' with its default value. See an example below.

.Starting a server on box serverbox in unicast mode on UDP port 12000:
[source,java]
----
AeronSubscriber subscriber = AeronSubscriber.create(new Context()
    .senderChannel("udp://serverbox:12000"));
----

==== Multiple sessions support for unicast

AeronSubscriber supports connections from several remote AeronPublishers launched
with different `Context.receiverChannel`.
Each AeronPublisher communicates with AeronSubscriber within its own session.
The demand is tracked by the subscriber per session.
A slow AeronPublisher connected to AeronSubscriber will eventually block a fast consuming one.
For the M1 a unicast session between AeronSubscriber and AeronPublisher requires a thread which is about
to change in a following release.

==== Multicast sending mode

To configure AeronSubscriber in multicast mode set field 'Context.receiverChannel' to a multicast Aeron channel.
Please refer to https://github.com/real-logic/Aeron/wiki/Channel-Configuration[Aeron Channel Configuration] guide for
more information regarding both multicast and unicast channel configurations.

.Starting a server on box serverbox in multicast mode on UDP port 12000:
[source,java]
----
AeronSubscriber subscriber = AeronSubscriber.create(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://239.1.1.1:12001"));
----

==== Multiple sessions support for multicast

As in case of unicast AeronSubscriber supports multiple sessions in multicast mode as well.
In multicast mode all sessions between an instance of AeronSubscriber and AeronPublishers
are handled in a single thread.

A slow AeronPublisher connected to AeronSubscriber will eventually backpressure the subscriber
and as a result a fast consuming publisher will block.

A single request for signals to upstream subscription of AeronSubscriber is made for
`Context.multicastUpstreamRequest`. Once signals are requested from the upstream they
are send into Aeron to all connected publishers and each publisher demand adjusted within its
session.

=== AeronPublisher as client

AeronPublisher plays a role of a client receiving signals from AeronSubscriber.
The publisher supports only a single subscriber. Therefore if you need to attach multiple subscriber then
`EmitterProcessor` should be put after the publisher.

The subscriber is configured via fields of `Context' which have default values and normally there is no need
to adjust them.

.Most important fields of `Context` for `AeronPublisher`
[cols="m,d", options="header"]
|======================================================
| Field                   | Description
| senderChannel           | Aeron channel used for connecting to an instance of `AeronSubscriber`
| receiverChannel         | Aeron channel used for receiving signals
| errorConsumer           | Consumer of errors encountered
| publicationRetryMillis  | Number of milliseconds to wait before giving up publishing of a message into Aeron. +
When publication fails the corresponding exception is reported into `errorConsumer`.
| heartbeatIntervalMillis | Interval in milliseconds for sending heartbeats from a signal receiver to a signal sender.
| maxHeartbeatPublicationFailures | Number of failed heartbeat publications after which AeronPublisher is shutdown
|======================================================

AeronPublisher requires both `Context.senderChannel` and `Context.receiverChannel` to be set.
`Context.senderChannel` should be set to the same value which was specified for the corresponding `AeronSubscriber`.

==== AeronProcessor

We introduced a reactive processor implementation as AeronProcessor.
The main feature of the processor is that it not only provides signals for its local subscribers
but also allows remote instances of AeronPublisher to connect and request signals for both
multicast and unicast modes of operation.

.An example of AeronProcessor usage
[source,java]
----
// Code run on a server machine with name serverbox:

AeronProcessor processor = ReactiveAeron.aeronProcessor(new Context()
    .senderChannel("udp://serverbox:12000"));

Subscriber subscriber = createSubscriber();

processor.subscribe(subscriber);


// Code run on a client machine with name clientbox:

AeronPublisher publisher = ReactiveAeron.aeronPublisher(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://clientbox:12001"));

Subscriber subscriber = createSubscriber();

publisher.subscribe(subscriber);
----

==== Unicast receiving mode

To connect to AeronSubscriber started in unicast sending mode it's required to set `Context.receiverChannel` to a value
in the following format: `udp://<Network Interface IP Address>|<hostname>:<Port>` +
where `Network Interface IP Address` is an IP address of a network interface used to receive signals from the network.
Alternatively `hostname` of the current machine can be used.

.Starting a client to be run on box clientbox on UDP port 12001 and connecting to the server on serverbox in unicast mode:
[source,java]
----
AeronPublisher publisher = AeronPublisher.create(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://clientbox:12001"));
----

==== Multicast receiving mode

To connect to AeronSubscriber in multicast sending mode set `Context.receiverChannel` to a multicast Aeron channel.

.Starting a client to be run on box clientbox on UDP port 12001 and connecting to the server on serverbox in multicast mode:
[source,java]
----
AeronPublisher publisher = AeronPublisher.create(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://239.1.1.1:12001"));
----

=== Heartbeats

AeronPublisher sends heartbeats to the instance of AeronSubscriber it is connected to
every `Context.heartbeatIntervalMillis' milliseconds. When the subscriber doesn't receive
any heartbeat from the publisher during the heartbeat interval * 1.5 it considers the session
with the publisher disconnected.

When the publisher can't publish a heartbeat to the subscriber `Context.maxHeartbeatPublicationFailures`
times in a row then it shuts itself down.

=== Auto-cancel functionality

Both AeronSubscriber and AeronPublisher support auto-cancel functionality.

When AeronSubscriber is created with `Context.autoCancel` set to true
it terminates its upstream subscription when the last publisher disconnects.

When AeronPublisher is created with `Context.autoCancel` set to true
it shuts itself down when its subscriber is terminated as it expects the
corresponding subscriber instance it's connecting to to operate in auto-cancel
mode as well.

=== Handling errors

Error handler can be specified via `Context.errorConsumer` and is set by default to an error consumer logging exceptions.

An exceptions received by the handler could be any descendant of `Throwable` including the following specific ones:
[cols="m,d", options="header"]
|=======================================================
| Exception                                | Description
| SignalPublicationFailedException         | When publication of any of Next, Error or Complete signals timed out on the server side.
| ServiceMessagePublicationFailedException | When publication of a service message like `.request(N)` or `.cancel()` timed out on the client side.
|=======================================================
