[[getting-started]]
== *Introducing Reactor IPC*

[quote, Preface, TL;DR]
Reactor IPC is a foundational library for building demanding, over the wire *Data-Streaming* applications and micro,
nano, or
 pico-services that must exhibit *Low-Latency* and be *Fault-Tolerant*.

[[start]]
=== What is Reactor IPC ?


=== About the Project

The project started in 2012, with a long internal incubation time. Reactor 1.x appeared in 2013. Reactor 1 has been deployed successfully by various organizations, both Open Source and commercial. In 2014 we started collaborating on the emerging <<gettingstarted.adoc/#reactivestreams,Reactive Streams Standard>> and started a massive re-engineering targeting April 2015 for version 2.0. The Reactive Streams Standard closed the last gap in our _Dispatching_ mechanism: controlling how much in-flight data was hitting Thread boundaries.

Parallel to that work we also decided to re-align some of our Event-Driven and Task Coordination API to the increasingly popular and documented <<gettingstarted.adoc/#rx,Reactive Extensions>>.

Reactor is https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 licensed]. It is available on https://github.com/reactor/reactor-ipc[GitHub].

=== Requirements

* Reactor needs at minimum Java 8 to execute.
** But the full expressive potential of functional composition happens with Java 8 Lambdas.
* Reactor runs at full capacity when the JVM supports *Unsafe* access (e.g., not the case for Android).
* Reactor is packaged as traditional JAR archives in Maven Central and can be pulled into any JVM project as a dependency using your preferred build tool.

[[architecture]]
=== Architecture Overview
.The main modules present in Reactor IPC