:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[http-client]]
= HTTP Client

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/http/client/HttpClient.html[`HttpClient`].
It hides most of the Netty functionality that is required to create a `HTTP` client
and adds Reactive Streams backpressure.

== Connect

To connect the `HTTP` client to a given `HTTP` endpoint, you must create and configure a
{javadoc}/reactor/netty/http/client/HttpClient.html[`HttpClient`] instance.
The following example shows how to do so:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()                   <1>
                          .get()                      <2>
                          .uri("http://example.com/") <3>
                          .response()                 <4>
                          .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/http/client/HttpClient.html[HttpClient]
instance ready for configuring.
<2> Specifies that `GET` method will be used.
<3> Specifies the path.
<4> Obtains the response {javadoc}/reactor/netty/http/client/HttpClientResponse.html[HttpClientResponse]
====


The following example uses `WebSocket`:

====
[source,java]
----
import io.netty.buffer.Unpooled;
import io.netty.util.CharsetUtil;
import reactor.core.publisher.Flux;
import reactor.netty.http.client.HttpClient;

public class Application {

    public static void main(String[] args) {
        HttpClient.create()
                  .websocket()
                  .uri("wss://echo.websocket.org")
                  .handle((inbound, outbound) -> {
                      inbound.receive()
                             .asString()
                             .take(1)
                             .subscribe(System.out::println);

                      final byte[] msgBytes = "hello".getBytes(CharsetUtil.ISO_8859_1);
                      return outbound.send(Flux.just(Unpooled.wrappedBuffer(msgBytes), Unpooled.wrappedBuffer(msgBytes)),
                                           b -> true)
                                     .neverComplete();
                  })
                  .blockLast();
    }
}
----
====

=== Host and Port

In order to connect to a specific host and port, you can apply the following configuration to the `HTTP` client:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .tcpConfiguration(tcpClient -> tcpClient.host("example.com")) <1>
                          .port(80)                                                     <2>
                          .get()
                          .uri("/")
                          .response()
                          .block();
    }
}
----
<1> Configures the `HTTP` host
<2> Configures the `HTTP` port
====

== Writing Data

To send data to a given `HTTP` endpoint, you can provide a `Publisher` by using the
{javadoc}/reactor/netty/http/client/HttpClient.RequestSender.html#send-org.reactivestreams.Publisher-[`send(Publisher)`] method.
By default, `Transfer-Encoding: chunked` is applied for those `HTTP` methods for which
a request body is expected. `Content-Length` provided through request headers disables `Transfer-Encoding: chunked`,
if necessary. The following example sends `hello`:

====
[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.ByteBufFlux;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .post()
                          .uri("http://example.com/")
                          .send(ByteBufFlux.fromString(Mono.just("hello"))) <1>
                          .response()
                          .block();
    }
}
----
<1> Sends a `hello` string to the given `HTTP` endpoint
====

=== Adding Headers and Other Metadata

When sending data to a given `HTTP` endpoint, you may need to send additional headers, cookies and other metadata.
You can use the following configuration to do so:

====
[source,java]
----
import io.netty.handler.codec.http.HttpHeaderNames;
import reactor.core.publisher.Mono;
import reactor.netty.ByteBufFlux;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .headers(h -> h.set(HttpHeaderNames.CONTENT_LENGTH, 5)) <1>
                          .post()
                          .uri("http://example.com/")
                          .send(ByteBufFlux.fromString(Mono.just("hello")))
                          .response()
                          .block();
    }
}
----
<1> Disables `Transfer-Encoding: chunked` and provides `Content-Length` header.
====

==== Compression

You can enable compression on the `HTTP` client, which means the request header
`Accept-Encoding` (or, in the case of WebSocket, the `Sec-Websocket-Extensions` header) is added
to the request headers. The following example shows how to do so:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .compress(true)
                          .get()
                          .uri("http://example.com/")
                          .response()
                          .block();
    }
}
----
====

==== Auto-Redirect Support

You can configure the `HTTP` client to enable auto-redirect support.

Reactor Netty provides two different strategies for auto-redirect support:

* `followRedirect(boolean)`: Specifies whether HTTP auto-redirect support is enabled for statuses `301|302|307|308`.
* `followRedirect(BiPredicate<HttpClientRequest, HttpClientResponse>)`: Enables auto-redirect support if the supplied
predicate matches.

The following example uses `followRedirect(true)`:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .followRedirect(true)
                          .get()
                          .uri("http://example.com/")
                          .response()
                          .block();
    }
}
----
====

== Consuming Data

To receive data from a given `HTTP` endpoint, you can use one of the methods from
{javadoc}/reactor/netty/http/client/HttpClient.ResponseReceiver.html[`HttpClient.ResponseReceiver`].
The following example uses the `responseContent` method:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;

public class Application {

    public static void main(String[] args) {
        String response =
                HttpClient.create()
                          .get()
                          .uri("http://example.com/")
                          .responseContent() <1>
                          .aggregate()       <2>
                          .asString()        <3>
                          .block();
    }
}
----
<1> Receives data from a given `HTTP` endpoint
<2> Aggregates the data
<3> Transforms the data as string
====

=== Reading Headers and Other Metadata

When receiving data from a given `HTTP` endpoint, you can check response headers, status code, and other metadata.
You can obtain this additional metadata by using
{javadoc}/reactor/netty/http/client/HttpClientResponse.html[`HttpClientResponse`].
The following example shows how to do so.

====
[source,java]
----
import reactor.netty.http.client.HttpClient;

public class Application {

    public static void main(String[] args) {
        String response =
                HttpClient.create()
                          .get()
                          .uri("http://example.com/")
                          .responseSingle((resp, bytes) -> {
                              System.out.println(resp.status()); <1>
                              return bytes.asString();
                          })
                          .block();
    }
}
----
<1> Obtains the status code.
====

=== HTTP Response Decoder

By default, `Netty` configures some restrictions for the incoming responses, such as:

* The maximum length of the initial line.
* The maximum length of all headers.
* The maximum length of the content or each chunk.

For more information, see https://netty.io/4.1/api/io/netty/handler/codec/http/HttpResponseDecoder.html[`HttpResponseDecoder`]

By default, the `HTTP` client is configured with the following settings:

====
[source,java,indent=0]
./../../main/java/reactor/netty/http/HttpDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/HttpDecoderSpec.java[lines=28..32]
----
====
====
[source,java,indent=0]
./../../main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/client/HttpResponseDecoderSpec.java[lines=34..36]
----
====

When you need to change these default settings, you can configure the `HTTP` client as follows:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;

public class Application {

    public static void main(String[] args) {
        String response =
                HttpClient.create()
                        .httpResponseDecoder(spec -> spec.maxHeaderSize(16384)) <1>
                        .get()
                        .uri("http://example.com/")
                        .responseContent()
                          .aggregate()
                          .asString()
                          .block();
    }
}
----
<1> The maximum length of all headers will be `16384`.
When this value is exceeded, a
https://netty.io/4.1/api/io/netty/handler/codec/TooLongFrameException.html[TooLongFrameException]
is raised.
====

== TCP-level Configurations

When you need configurations on a TCP level, you can use the following snippet
to extend the default `TCP` client configuration:

====
[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .tcpConfiguration(tcpClient ->
                                  tcpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000))
                          .get()
                          .uri("http://example.com/")
                          .response()
                          .block();
    }
}
----
====

See <<tcp-client>> for more about `TCP` level configurations.

=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers needs to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.http.client.HttpClient` level to `DEBUG`
and apply the following configuration:

====
[source,java]
----
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .wiretap(true) <1>
                          .get()
                          .uri("http://example.com/")
                          .response()
                          .block();
    }
}
----
<1> Enables the wire logging
====

== SSL andTLS
When you need SSL or TLS, you can apply the configuration shown in the next example.
By default, if `OpenSSL` is available, a
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
provider is used as a provider. Otherwise a
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[SslProvider.JDK] provider is used
You can switch the provider by using
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.
The following example uses `SslContextBuilder`:

====
[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientResponse;

public class Application {

    public static void main(String[] args) {
        HttpClientResponse response =
                HttpClient.create()
                          .secure(spec -> spec.sslContext(SslContextBuilder.forClient()))
                          .get()
                          .uri("https://example.com/")
                          .response()
                          .block();
    }
}
----
====

== Retry Strategies
By default, the `HTTP` client retries the request once if it was aborted on the `TCP` level.
