:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[http-server]]
= HTTP Server
`Reactor Netty` provides easy to use and configure
{javadoc}/reactor/netty/http/server/HttpServer.html[HttpServer].
It hides most of the `Netty` functionality that is needed in order to create a `HTTP` server,
and in addition adds `Reactive Streams` backpressure.

== Start and Stop
To start an HTTP server, {javadoc}/reactor/netty/http/server/HttpServer.html[HttpServer]
instance has to be created and configured.
By default the `host` will be configured for any local address and the system will pick up an ephemeral port
when the `bind` operation is invoked:

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()   <1>
                          .bindNow(); <2>

        server.onDispose()
              .block();
    }
}
----
<1> Creates an {javadoc}/reactor/netty/http/server/HttpServer.html[HttpServer]
instance ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.

The returned {javadoc}/reactor/netty/DisposableServer.html[DisposableServer]
offers simple server API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[disposeNow()]
which shuts the server down in a blocking fashion.

=== Host and Port
To serve on a specific `host` and `port`, the configuration below can be applied to the `HTTP` server:

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .host("localhost") <1>
                          .port(8080)        <2>
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the `HTTP` server host
<2> Configures the `HTTP` server port

== Routing HTTP
Defining routes for the `HTTP` server is as easy as just configuring the provided
{javadoc}/reactor/netty/http/server/HttpServerRoutes.html[HttpServerRoutes] builder.

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .route(routes ->
                              routes.get("/hello",        <1>
                                         (request, response) -> response.sendString(Mono.just("Hello World!")))
                                    .post("/echo",        <2>
                                         (request, response) -> response.send(request.receive().retain()))
                                    .get("/path/{param}", <3>
                                         (request, response) -> response.sendString(Mono.just(request.param("param"))))
                                    .ws("/ws",            <4>
                                         (wsInbound, wsOutbound) -> wsOutbound.send(wsInbound.receive().retain())))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Serves a `GET` request to `/hello` and returns `Hello World!`
<2> Serves a `POST` request to `/echo` and returns as a response, the received request body.
<3> Serves a `GET` request to `/path/{param}` and returns the value of the path parameter.
<4> Serves websocket to `/ws` and returns as an outgoing data, the received incoming data.

NOTE: The server routes are unique and only the first matching in order of declaration will be invoked.

=== SSE
The code below shows how the `HTTP` server might be configured in order to serve `Server-Sent Events`.

[source,java]
----
import com.fasterxml.jackson.databind.ObjectMapper;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import org.reactivestreams.Publisher;
import reactor.core.publisher.Flux;
import reactor.netty.DisposableServer;
import reactor.netty.NettyPipeline;
import reactor.netty.http.server.HttpServer;
import reactor.netty.http.server.HttpServerRequest;
import reactor.netty.http.server.HttpServerResponse;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;
import java.time.Duration;
import java.util.function.BiFunction;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .route(routes -> routes.get("/sse", serveSse()))
                          .bindNow();

        server.onDispose()
              .block();
    }

    /**
     * Prepares SSE response
     * The "Content-Type" is "text/event-stream"
     * The flushing strategy is "flush after every element" emitted by the provided Publisher
     */
    private static BiFunction<HttpServerRequest, HttpServerResponse, Publisher<Void>> serveSse() {
        Flux<Long> flux = Flux.interval(Duration.ofSeconds(10));
        return (request, response) ->
            response.sse()
                    .options(NettyPipeline.SendOptions::flushOnEach)
                    .send(flux.map(Application::toByteBuf));
    }

    /**
     * Transforms the Object to ByteBuf following the expected SSE format.
     */
    private static ByteBuf toByteBuf(Object any) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            out.write("data: ".getBytes(Charset.defaultCharset()));
            MAPPER.writeValue(out, any);
            out.write("\n\n".getBytes(Charset.defaultCharset()));
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
        return ByteBufAllocator.DEFAULT
                               .buffer()
                               .writeBytes(out.toByteArray());
    }

    private static final ObjectMapper MAPPER = new ObjectMapper();
}
----

=== Static Resources
The code below shows how the `HTTP` server might be configured in order to serve static resources.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .route(routes -> routes.file("/index.html", pathToFile))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

== Writing Data
In order to send data to a connected client, an I/O handler has to be attached either using
{javadoc}/reactor/netty/http/server/HttpServer.html#handle-java.util.function.BiFunction-[handle(...)] or
{javadoc}/reactor/netty/http/server/HttpServer.html#route-java.util.function.Consumer-[route(...)] methods.
The I/O handler has access to {javadoc}/reactor/netty/http/server/HttpServerResponse.html[HttpServerResponse]
in order to be able to write data.

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .handle((request, response) -> response.sendString(Mono.just("hello"))) <1>
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Sends `hello` string to the connected clients

=== Adding Headers and other Metadata
When sending data to the connected clients, additional headers, cookies, status code etc.
might be necessary. This additional metadata can be provided using
{javadoc}/reactor/netty/http/server/HttpServerResponse.html[HttpServerResponse]

[source,java]
----
import io.netty.handler.codec.http.HttpHeaderNames;
import io.netty.handler.codec.http.HttpResponseStatus;
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .route(routes ->
                              routes.get("/hello",
                                         (request, response) ->
                                             response.status(HttpResponseStatus.OK)
                                                     .header(HttpHeaderNames.CONTENT_LENGTH, "12")
                                                     .sendString(Mono.just("Hello World!"))))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

=== Compression
The `HTTP` server can be configured to send a compressed response depending on the request header
`Accept-Encoding` or in case of websocket the `Sec-Websocket-Extensions` header.

`Reactor Netty` provides three different strategies for compressing the outgoing data:

* `compress(boolean)` - depending on the boolean that is provided the compression will be enabled or disabled.
* `compress(int)` - the compression will be performed once response size exceeds the given value in bytes.
* `compress(BiPredicate<HttpServerRequest, HttpServerResponse>)` - the compression will be performed if
the predicate returns `true`.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .compress(true)
                          .route(routes -> routes.file("/index.html", pathToFile))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

== Flushing Strategies
`Reactor Netty` provides three different strategies for flushing the outgoing data
{javadoc}/reactor/netty/NettyPipeline.SendOptions.html[NettyPipeline.SendOptions]

* `flushOnBoundary()` - this is the default behaviour. The flush operation will be explicitly invoked on a terminated `Publisher`.
* `flushOnEach()` - The flushing operation will be executed as soon as possible after the write operation.
This means that the ultimate goal is a flush operation after every element that was written, however as the flush operation
will be scheduled, the flush operation might be invoked once for several write operations.
* `flushOnEach(boolean)` - Depending on the provided boolean, the flush operation might behave as the one described above
(when invoked with `true`), or (when invoked with `false`) it is guaranteed that there will be a flush operation after
every write operation.

[source,java]
----
import reactor.core.publisher.Flux;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .handle((request, response) ->
                                  response.options(o -> o.flushOnEach(false)) <1>
                                          .sendString(Flux.just("Hello", "World", "!")))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the flushing strategy to flush after every element emitted by the given `Publisher`.
The flush operation will not be scheduled, which means flush operation will be invoked after every write operation.

NOTE: There might be an implicit flushing when the buffer used for the outgoing data is full.
The buffer size can be configured using the channel option `SO_SNDBUF`.

== Consuming Data
In order to receive data from a connected client, an I/O handler has to be attached either using
{javadoc}/reactor/netty/http/server/HttpServer.html#handle-java.util.function.BiFunction-[handle(...)] or
{javadoc}/reactor/netty/http/server/HttpServer.html#route-java.util.function.Consumer-[route(...)] methods.
The I/O handler has access to {javadoc}/reactor/netty/http/server/HttpServerRequest.html[HttpServerRequest]
in order to be able to read data.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .handle((request, response) -> request.receive().then()) <1>
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Receives data from the connected clients

=== Reading Headers, URI Params and other Metadata
When receiving data from the connected clients, request headers, parameters etc.
might need to be checked. This additional metadata can be obtained using
{javadoc}/reactor/netty/http/server/HttpServerRequest.html[HttpServerRequest]

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .route(routes ->
                              routes.get("/{param}",
                                         (request, response) -> {
                                             if (request.requestHeaders().contains("Some-Header")) {
                                                 return response.sendString(Mono.just(request.param("param")));
                                             }
                                             return response.sendNotFound();
                                         }))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

==== Obtaining the Remote (Client) Address
In addition to the metadata above that can be obtained from the request, the `host (server)` address, the `remote (client)`
address and the `scheme` also can be received. Depending on the chosen factory method, the information
can be retrieved directly from the channel or additionally using the `Forwarded` or `X-Forwarded-*` `HTTP` request headers.

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .forwarded(true) <1>
                          .route(routes ->
                              routes.get("/clientip",
                                         (request, response) ->
                                             response.sendString(Mono.just(request.remoteAddress() <2>
                                                                                  .getHostString()))))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Specifies that the information about the connection will be obtained from the `Forwarded` and `X-Forwarded-*`
`HTTP` request headers if possible.
<2> Returns the address of the remote (client) peer.

=== HTTP Request Decoder
By default `Netty` configures some restrictions for the incoming requests, such as:

* The maximum length of the initial line.
* The maximum length of all headers.
* The maximum length of the content or each chunk.

For more information check https://netty.io/4.1/api/io/netty/handler/codec/http/HttpRequestDecoder.html[HttpRequestDecoder]

By default the `HTTP` server is configured with the settings below:

[source,java,indent=0]
./../../main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
----
include::{sourcedir}/reactor/netty/http/server/HttpRequestDecoderSpec.java[lines=33..37]
----

When these default settings have to be changed, the `HTTP` server can be configured as follows:

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .httpRequestDecoder(spec -> spec.maxHeaderSize(16384)) <1>
                          .handle((request, response) -> response.sendString(Mono.just("hello"))) <1>
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> The maximum length of all headers will be `16384`,
when this value is exceeded, https://netty.io/4.1/api/io/netty/handler/codec/TooLongFrameException.html[TooLongFrameException] will be raised.

== TCP Level Configurations
When configurations on a TCP level are needed the snippet below can be used in order
to extend the default `TCP` server configuration:

[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .tcpConfiguration(tcpServer ->
                                  tcpServer.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

Refer to <<tcp-server>> for more details about `TCP` level configurations.

=== Wire Logger
`Reactor Netty` provides a wire logging when the traffic between the peers needs to be inspected.
Bye default the wire logging is disabled.
In order to be enabled it, the logger `reactor.netty.http.server.HttpServer` level has to be set to `DEBUG`
and the configuration below to be applied.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .wiretap(true) <1>
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Enables the wire logging

== SSL/TLS
When `SSL/TLS` is needed the configuration below can be applied.

[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.DisposableServer;
import reactor.netty.http.server.HttpServer;
import java.io.File;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .secure(spec ->
                                  SslContextBuilder.forServer(new File("certificate.crt"),
                                                              new File("private.key")))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

== HTTP Access Log
The current support provides only https://en.wikipedia.org/wiki/Common_Log_Format[Common Log Format].

`-Dreactor.netty.http.server.accessLogEnabled=true` can be used in order to enable the `HTTP` access log.
By default it is disabled.

The configuration below (logback) or similar (other logging frameworks) can be used to have a separate
`HTTP` access log file:

[source,xml]
----
<appender name="accessLog" class="ch.qos.logback.core.FileAppender">
    <file>access_log.log</file>
    <encoder>
        <pattern>%msg%n</pattern>
    </encoder>
</appender>
<appender name="async" class="ch.qos.logback.classic.AsyncAppender">
    <appender-ref ref="accessLog" />
</appender>

<logger name="reactor.netty.http.server.AccessLog" level="INFO" additivity="false">
    <appender-ref ref="async"/>
</logger>
----

== HTTP/2
By default the `HTTP` server supports `HTTP/1.1`, if `HTTP/2` is needed, it has to be configured.
In addition to the protocol configuration, if `H2` is needed and not `H2C (cleartext)`, SSL also has to be configured.

NOTE: As that protocol is not supported `out-of-the-box` by JDK8, an additional dependency to a native library that
supports it might be needed as for example https://netty.io/wiki/forked-tomcat-native.html[netty-tcnative-boringssl-static]

Simple `H2` example:
[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.HttpProtocol;
import reactor.netty.http.server.HttpServer;
import java.io.File;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .port(8080)
                          .protocol(HttpProtocol.H2) <1>
                          .secure(spec ->            <2>
                                  SslContextBuilder.forServer(new File("certificate.crt"),
                                                              new File("private.key")))
                          .handle((request, response) -> response.sendString(Mono.just("hello")))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the server to support only `HTTP/2`
<2> Configures `SSL`

The application should now behave like this:
[source,bash]
----
$ curl --http2 https://localhost:8080 -i
HTTP/2 200

hello
----

Simple `H2C` example:
[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.HttpProtocol;
import reactor.netty.http.server.HttpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                HttpServer.create()
                          .port(8080)
                          .protocol(HttpProtocol.H2C)
                          .handle((request, response) -> response.sendString(Mono.just("hello")))
                          .bindNow();

        server.onDispose()
              .block();
    }
}
----

The application should now behave like this:
[source,bash]
----
$ curl --http2-prior-knowledge http://localhost:8080 -i
HTTP/2 200

hello
----