= Reactor Netty Reference Guide
Stephane Maldini <https://twitter.com/smaldini[@smaldini]>; Violeta Georgieva <https://twitter.com/violeta_g_g[@violeta_g_g]>
ifndef::host-github[:ext-relative: {outfilesuffix}]
:doctype: book
:icons: font
:toc2:
:sectnums:
:sectanchors:

include::about-doc.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/about-doc.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<about-doc>>"
endif::[]

include::getting-started.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/getting-started.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<getting-started>>"
endif::[]

include::tcp-server.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/tcp-server.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<tcp-server>>"
endif::[]

include::tcp-client.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/tcp-client.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<tcp-client>>"
endif::[]

include::http-server.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/http-server.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<http-server>>"
endif::[]

include::http-client.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/http-client.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<http-client>>"
endif::[]

include::udp-server.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/udp-server.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<udp-server>>"
endif::[]

include::udp-client.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-netty/edit/master/src/docs/asciidoc/udp-client.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<udp-client>>"
endif::[]

