:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-server]]
= TCP Server
`Reactor Netty` provides easy to use and configure
{javadoc}/reactor/netty/tcp/TcpServer.html[TcpServer].
It hides most of the `Netty` functionality that is needed in order to create a `TCP` server,
and in addition adds `Reactive Streams` backpressure.

== Start and Stop
To start a `TCP` server, a {javadoc}/reactor/netty/tcp/TcpServer.html[TcpServer]
instance has to be created and configured.
By default the `host` will be configured for any local address and the system will pick up an ephemeral port
when the `bind` operation is invoked:

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()   <1>
                         .bindNow(); <2>

        server.onDispose()
              .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/tcp/TcpServer.html[TcpServer]
instance ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.

The returned {javadoc}/reactor/netty/DisposableServer.html[DisposableServer]
offers simple server API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[disposeNow()]
which shuts the server down in a blocking fashion.

=== Host and Port
In order to serve on a specific `host` and `port`, the configuration below can be applied to the `TCP` server:

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .host("localhost") <1>
                         .port(8080)        <2>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the `TCP` server host
<2> Configures the `TCP` server port

== Writing Data
In order to send data to a connected client, an I/O handler has to be attached.
The I/O handler has access to {javadoc}/reactor/netty/NettyOutbound.html[NettyOutbound]
in order to be able to write data.

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) -> outbound.sendString(Mono.just("hello"))) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Sends `hello` string to the connected clients

== Flushing Strategies
`Reactor Netty` provides three different strategies for flushing the outgoing data
{javadoc}/reactor/netty/NettyPipeline.SendOptions.html[NettyPipeline.SendOptions]

* `flushOnBoundary()` - this is the default behaviour. The flush operation will be explicitly invoked on a terminated `Publisher`.
* `flushOnEach()` - The flushing operation will be executed as soon as possible after the write operation.
This means that the ultimate goal is a flush operation after every element that was written, however as the flush operation
will be scheduled, the flush operation might be invoked once for several write operations.
* `flushOnEach(boolean)` - Depending on the provided boolean, the flush operation might behave as the one described above
(when invoked with `true`), or (when invoked with `false`) it is guaranteed that there will be a flush operation after
every write operation.

[source,java]
----
import reactor.core.publisher.Flux;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) ->
                                 outbound.options(o -> o.flushOnEach(false)) <1>
                                         .sendString(Flux.just("Hello", "World", "!")))
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the flushing strategy to flush after every element emitted by the given `Publisher`.
The flush operation will not be scheduled, which means flush operation will be invoked after every write operation.

NOTE: There might be an implicit flushing when the buffer used for the outgoing data is full.
The buffer size can be configured using the channel option `SO_SNDBUF`.

== Consuming Data
In order to receive data from a connected client, an I/O handler has to be attached.
The I/O handler has access to {javadoc}/reactor/netty/NettyInbound.html[NettyInbound]
in order to be able to read data.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) -> inbound.receive().then()) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Receives data from the connected clients

== Lifecycle Callbacks
The lifecycle callbacks below are provided in order to be able to extend the `TCP` server.

* `doOnBind` - The callback is invoked when the server channel is about to bind.
* `doOnBound` - The callback is invoked when the server channel is bound.
* `doOnConnection` - The callback is invoked when a remote client is connected
* `doOnUnbound` - The callback is invoked when the server channel is unbound.
* `doOnLifecycle` - Setups all lifecycle callbacks

[source,java]
----
import io.netty.handler.timeout.ReadTimeoutHandler;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;
import java.util.concurrent.TimeUnit;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .doOnConnection(conn ->
                                 conn.addHandler(new ReadTimeoutHandler(10, TimeUnit.SECONDS))) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when a remote client is connected.

== TCP Level Configurations

=== Channel Options
By default the `TCP` server is configured with the options below:

[source,java,indent=0]
./../../main/java/reactor/netty/tcp/TcpServerBind.java
----
include::{sourcedir}/reactor/netty/tcp/TcpServerBind.java[lines=126..138]
----

If additional options are necessary or changes to the current options, the configuration below can be applied:

[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----

More about `Netty` channel options can be found on the link below:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[ChannelOption]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[SocketOptions]

=== Wire Logger
`Reactor Netty` provides a wire logging when the traffic between the peers has to be inspected.
By default the wire logging is disabled.
In order to be enabled it, the logger `reactor.netty.tcp.TcpServer` level has to be set to `DEBUG`
and the configuration below has to be applied.

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .wiretap(true) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Enables the wire logging

=== Event Loop Group
By default the `TCP` server will use `Event Loop Group` where the number of the worker threads will be the number of
processors available to the runtime on init (but with a minimum value of 4). When a different configuration is needed,
one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods can be used.

The default configuration for the `Event Loop Group` is the following:

[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=670..690]
----

If changes to the these settings are needed, the configuration below can be applied:

[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.resources.LoopResources;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        DisposableServer server =
                TcpServer.create()
                         .runOn(loop)
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----

== SSL/TLS
When `SSL/TLS` is needed the configuration below can be applied.

[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;
import java.io.File;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .secure(spec ->
                                 SslContextBuilder.forServer(new File("certificate.crt"),
                                                             new File("private.key")))
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
