:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-client]]
= TCP Client

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/tcp/TcpClient.html[`TcpClient`].
It hides most of the Netty functionality that is needed in order to create a `TCP` client
and adds Reactive Streams backpressure.

== Connect and Disconnect

To connect the `TCP` client to a given endpoint, you must create and configure a
{javadoc}/reactor/netty/tcp/TcpClient.html[`TcpClient`] instance.
By default, the `host` is `localhost` and the `port` is `12012`.
The following example shows how to create a `TcpClient`:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()      <1>
                         .connectNow(); <2>

        connection.onDispose()
                  .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/tcp/TcpClient.html[`TcpClient`]
instance that is ready for configuring.
<2> Connects the client in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/Connection.html[`Connection`]
offers a simple connection API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the client down in a blocking fashion.

=== Host and Port

To connect to a specific `host` and `port`, you can apply the following configuration to the `TCP` client.
The following example shows how to do so:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com") <1>
                         .port(80)            <2>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Configures the `HTTP` host
<2> Configures the `HTTP` port
====

== Writing Data

To send data to a given endpoint, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyOutbound.html[`NettyOutbound`]
to be able to write data.

====
[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((inbound, outbound) -> outbound.sendString(Mono.just("hello"))) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Sends `hello` string to the endpoint.
====

== Consuming Data

To receive data from a given endpoint, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyInbound.html[`NettyInbound`]
to be able to read data. The following example shows how to do so:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((inbound, outbound) -> inbound.receive().then()) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Receives data from a given endpoint
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `TCP` client.

* `doOnConnect`: Invoked when the channel is about to connect.
* `doOnConnected`: Invoked after the channel has been connected.
* `doOnDisconnected`: Invoked after the channel has been disconnected.
* `doOnLifecycle`: Sets up all lifecycle callbacks.

The following example uses the `doOnConnected` callback:

====
[source,java]
----
import io.netty.handler.timeout.ReadTimeoutHandler;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;
import java.util.concurrent.TimeUnit;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .doOnConnected(conn ->
                                 conn.addHandler(new ReadTimeoutHandler(10, TimeUnit.SECONDS))) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when the channel has been connected.
====

== TCP-level Configurations

This section describes three kinds of configuration that you can use at the TCP level:

* <<client-tcp-level-configurations-channel-options>>
* <<client-tcp-level-configurations-event-wire-logger>>
* <<client-tcp-level-configurations-event-loop-group>>

[[client-tcp-level-configurations-channel-options]]
=== Channel Options

By default, the `TCP` client is configured with the following options:

====
[source,java,indent=0]
./../../main/java/reactor/netty/tcp/TcpClient.java
----
include::{sourcedir}/reactor/netty/tcp/TcpClient.java[lines=617..619]
----
====

If additional options are necessary or changes to the current options, you can apply the following configuration:

====
[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

You can find more about `Netty` channel options at the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[client-tcp-level-configurations-event-wire-logger]]
=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.tcp.TcpClient` level to `DEBUG`
and apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .wiretap(true) <1>
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Enables the wire logging
====

[[client-tcp-level-configurations-event-loop-group]]
=== Event Loop Group

By default the `TCP` client uses an "`Event Loop Group`", where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods.

The following listing shows the default configuration for the Event Loop Group:

====
[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=75..95]
----
====

If you need changes to the these settings, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.LoopResources;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .runOn(loop)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

== Connection Pool

By default, the `TCP` client uses a "`fixed`" connection pool with `500` as the maximum number of the channels and
`45s` as the acquisition timeout.
This means that the implementation creates a new channel if someone tries to acquire a channel but none is in the pool.
When the maximum number of the channels in the pool is reached, new tries to acquire a channel are delayed
until a channel is returned to the pool again.
The implementation uses `FIFO` order for channels in the pool regardless of whether it is "`elastic`" or "`fixed`".
By default, there is no idle time specified for the channels in the pool.

If you need an "`elastic`" connection pool, you can apply the following configuration by using
{javadoc}/reactor/netty/resources/ConnectionProvider.html[`ConnectionProvider`].
The following example shows how to do so:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.ConnectionProvider;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        ConnectionProvider provider = ConnectionProvider.elastic("fixed");
        Connection connection =
                TcpClient.create(provider)
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

If you need to disable the connection pool, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.newConnection()
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

If you need to specify an idle time for the channels in the connection pool, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.ConnectionProvider;
import reactor.netty.tcp.TcpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        ConnectionProvider provider = ConnectionProvider.fixed("fixed", 50, 30000, Duration.ofSeconds(60));
        Connection connection =
                TcpClient.create(provider)
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

NOTE: Be cautious with an "`elastic`" connection pool when you expect a high load. You might experience
`reactor.netty.http.client.PrematureCloseException` exception with a root cause "Connect Timeout" due
to too many concurrent connections opened/acquired.

== SSL and TLS

When you need SSL or TLS, you can apply the following configuration.
By default, if `OpenSSL` is available, the
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
provider is used as a provider. Otherwise, the provider is
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[`SslProvider.JDK`].
You can switch the provider by using
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.

The following example uses `SslContextBuilder`:

====
[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(443)
                         .secure(spec -> spec.sslContext(SslContextBuilder.forClient()))
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====

== Proxy Support

The TCP client supports the proxy functionality provided by Netty and provides a way
to specify "`non proxy hosts`" through the {javadoc}/reactor/netty/tcp/ProxyProvider.html[`ProxyProvider`] builder.
The following example uses `ProxyProvider`:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.ProxyProvider;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS4)
                                            .host("proxy")
                                            .port(8080)
                                            .nonProxyHosts("localhost"))
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
====
