:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-client]]
= TCP Client
`Reactor Netty` provides easy to use and configure
{javadoc}/reactor/netty/tcp/TcpClient.html[TcpClient].
It hides most of the `Netty` functionality that is needed in order to create a `TCP` client,
and in addition adds `Reactive Streams` backpressure.

== Connect and Disconnect
To connect the `TCP` client to a given endpoint, a {javadoc}/reactor/netty/tcp/TcpClient.html[TcpClient]
instance has to be created and configured.
By default the `host` will be configured for `localhost` and the `port` will be `12012`:

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()      <1>
                         .connectNow(); <2>

        connection.onDispose()
                  .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/tcp/TcpClient.html[TcpClient]
instance ready for configuring.
<2> Connects the client in a blocking fashion and waits for it to finish initializing.

The returned {javadoc}/reactor/netty/Connection.html[Connection]
offers simple connection API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[disposeNow()]
which shuts the client down in a blocking fashion.

=== Host and Port
In order to connect to a specific `host` and `port`, the configuration below can be applied to the `TCP` client:

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com") <1>
                         .port(80)            <2>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Configures the `HTTP` host
<2> Configures the `HTTP` port

== Writing Data
In order to send data to a given endpoint, an I/O handler has to be attached.
The I/O handler has access to {javadoc}/reactor/netty/NettyOutbound.html[NettyOutbound]
in order to be able to write data.

[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((inbound, outbound) -> outbound.sendString(Mono.just("hello"))) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Sends `hello` string to the endpoint.

== Flushing Strategies
`Reactor Netty` provides three different strategies for flushing the outgoing data
{javadoc}/reactor/netty/NettyPipeline.SendOptions.html[NettyPipeline.SendOptions]

* `flushOnBoundary()` - this is the default behaviour. The flush operation will be explicitly invoked on a terminated `Publisher`.
* `flushOnEach()` - The flushing operation will be executed as soon as possible after the write operation.
This means that the ultimate goal is a flush operation after every element that was written, however as the flush operation
will be scheduled, the flush operation might be invoked once for several write operations.
* `flushOnEach(boolean)` - Depending on the provided boolean, the flush operation might behave as the one described above
(when invoked with `true`), or (when invoked with `false`) it is guaranteed that there will be a flush operation after
every write operation.

[source,java]
----
import reactor.core.publisher.Flux;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((inbound, outbound) ->
                                 outbound.options(o -> o.flushOnEach(false)) <1>
                                         .sendString(Flux.just("Hello", "World", "!")))
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Configures the flushing strategy to flush after every element emitted by the given `Publisher`.
The flush operation will not be scheduled, which means flush operation will be invoked after every write operation.

NOTE: There might be an implicit flushing when the buffer used for the outgoing data is full.
The buffer size can be configured using the channel option `SO_SNDBUF`.

== Consuming Data
In order to receive data from a given endpoint, an I/O handler has to be attached.
The I/O handler has access to {javadoc}/reactor/netty/NettyInbound.html[NettyInbound]
in order to be able to read data.

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((inbound, outbound) -> inbound.receive().then()) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Receives data from a given endpoint

== Lifecycle Callbacks
The lifecycle callbacks below are provided in order to be able to extend the `TCP` client.

* `doOnConnect` - The callback is invoked when the channel is about to connect.
* `doOnConnected` - The callback is invoked after the channel has been connected.
* `doOnDisconnected` - The callback is invoked after the channel has been disconnected.
* `doOnLifecycle` - Setups all lifecycle callbacks

[source,java]
----
import io.netty.handler.timeout.ReadTimeoutHandler;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;
import java.util.concurrent.TimeUnit;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .doOnConnected(conn ->
                                 conn.addHandler(new ReadTimeoutHandler(10, TimeUnit.SECONDS))) <1>
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when the channel has been connected.

== TCP Level Configurations

=== Channel Options
By default the `TCP` client is configured with the options below:

[source,java,indent=0]
./../../main/java/reactor/netty/tcp/TcpClient.java
----
include::{sourcedir}/reactor/netty/tcp/TcpClient.java[lines=573..581]
----

If additional options are necessary or changes to the current options, the configuration below can be applied:

[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----

More about `Netty` channel options can be found on the link below:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[ChannelOption]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[SocketOptions]

=== Wire Logger
`Reactor Netty` provides a wire logging when the traffic between the peers has to be inspected.
By default the wire logging is disabled.
In order to be enabled it, the logger `reactor.netty.tcp.TcpClient` level has to be set to `DEBUG`
and the configuration below has to be applied.

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .wiretap(true) <1>
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
<1> Enables the wire logging

=== Event Loop Group
By default the `TCP` client will use `Event Loop Group` where the number of the worker threads will be the number of
processors available to the runtime on init (but with a minimum value of 4). When a different configuration is needed,
one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods can be used.

The default configuration for the `Event Loop Group` is the following:

[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=670..690]
----

If changes to the these settings are needed, the configuration below can be applied:

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.LoopResources;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .runOn(loop)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----

== Connection Pool
By default the `TCP` client uses `elastic` connection pool. This means that the implementation will create a new channel
if someone tries to acquire a channel but none is in the pool. Also there is no limit on the maximal concurrent channels.
The implementation uses `FIFO` order for channels in the pool regardless it is `elastic` or `fixed`.

If a `fixed` connection pool is needed then the configuration below can be applied using
{javadoc}/reactor/netty/resources/ConnectionProvider.html[ConnectionProvider]:

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.ConnectionProvider;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        ConnectionProvider provider = ConnectionProvider.fixed("fixed", 50, 30000);
        Connection connection =
                TcpClient.create(provider)
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----

If the connection pool has to be disabled then the configuration below can be applied:
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.newConnection()
                         .host("example.com")
                         .port(80)
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----

== SSL/TLS
When `SSL/TLS` is needed the configuration below can be applied.
By default if `OpenSSL` is available
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[SslProvider.html#OPENSSL]
provider will be used as a provider, otherwise
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[SslProvider.html#JDK].
Switching the provider can be done via
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[SslContextBuilder]
or setting `-Dio.netty.handler.ssl.noOpenSsl=true`

[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.Connection;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(443)
                         .secure(spec -> spec.sslContext(SslContextBuilder.forClient()))
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----

== Proxy Support
The `TCP` client supports the proxy functionality provided by `Netty` and in addition provides a way
to specify `non proxy hosts` via {javadoc}/reactor/netty/tcp/ProxyProvider.html[ProxyProvider] builder.

[source,java]
----
import reactor.netty.Connection;
import reactor.netty.tcp.ProxyProvider;
import reactor.netty.tcp.TcpClient;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                TcpClient.create()
                         .host("example.com")
                         .port(80)
                         .proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS4)
                                            .host("proxy")
                                            .port(8080)
                                            .nonProxyHosts("localhost"))
                         .connectNow();

        connection.onDispose()
                  .block();
    }
}
----
