:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-server]]
= TCP Server

`Reactor Netty` provides an easy to use and configure
{javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`].
It hides most of the `Netty` functionality that is needed to create a `TCP` server
and adds `Reactive Streams` backpressure.

== Starting and Stopping

To start a `TCP` server, you must create and configure a
{javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`] instance.
By default, the `host` is configured for any local address, and the system picks up an ephemeral port
when the `bind` operation is invoked. The folloiwng example shows how to create and
configure a `TcpServer` instance:

====
[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()   <1>
                         .bindNow(); <2>

        server.onDispose()
              .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`]
instance that is ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/DisposableServer.html[`DisposableServer`]
offers a simple server API, including {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the server down in a blocking fashion.

=== Host and Port

To serve on a specific `host` and `port`, you can apply the following configuration to the `TCP` server:

====
[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .host("localhost") <1>
                         .port(8080)        <2>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the `TCP` server host
<2> Configures the `TCP` server port
====

== Writing Data

In order to send data to a connected client, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyOutbound.html[`NettyOutbound`]
to be able to write data. The following example shows how to attach an I/O handler:

====
[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) -> outbound.sendString(Mono.just("hello"))) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Sends `hello` string to the connected clients
====

== Flushing Strategies

`Reactor Netty` provides three different strategies for flushing the outgoing data, as detailed in
{javadoc}/reactor/netty/NettyPipeline.SendOptions.html[`NettyPipeline.SendOptions`]:

* `flushOnBoundary()` (default): The flush operation is explicitly invoked on a terminated `Publisher`.
* `flushOnEach()`: The flushing operation is invoked as soon as possible after the write operation.
This means that the ultimate goal is a flush operation after every element that was written.
However, as the flush operation is scheduled, the flush operation might be invoked once for several write operations.
* `flushOnEach(boolean)`: Depending on the provided boolean value, the flush operation might behave as the one described above
(when invoked with `true`), or (when invoked with `false`) it is guaranteed that a flush operation happens after
every write operation.

The following example sets the flushing strategy to `flushOnEach(false)`:

====
[source,java]
----
import reactor.core.publisher.Flux;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) ->
                                 outbound.options(o -> o.flushOnEach(false)) <1>
                                         .sendString(Flux.just("Hello", "World", "!")))
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Configures the flushing strategy to flush after every element emitted by the given `Publisher`.
The flush operation is not scheduled, which means the flush operation is invoked after every write operation.
====

NOTE: There might be an implicit flushing when the buffer used for the outgoing data is full.
You can configure the buffer size by using the `SO_SNDBUF` channel option.

== Consuming Data

In order to receive data from a connected client, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/NettyInbound.html[`NettyInbound`]
to be able to read data. The following example shows how to use it:

====
[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .handle((inbound, outbound) -> inbound.receive().then()) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Receives data from the connected clients
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `TCP` server:

* `doOnBind`: Invoked when the server channel is about to bind.
* `doOnBound`: Invoked when the server channel is bound.
* `doOnConnection`: Invoked when a remote client is connected
* `doOnUnbound`: Invoked when the server channel is unbound.
* `doOnLifecycle`: Sets up all lifecycle callbacks.

The following example uses the `doOnConnection` callback:

====
[source,java]
----
import io.netty.handler.timeout.ReadTimeoutHandler;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;
import java.util.concurrent.TimeUnit;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .doOnConnection(conn ->
                                 conn.addHandler(new ReadTimeoutHandler(10, TimeUnit.SECONDS))) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> `Netty` pipeline is extended with `ReadTimeoutHandler` when a remote client is connected.
====

== TCP-level Configurations

This section describes three kinds of configuration that you can use at the TCP level:

* <<server-tcp-level-configurations-channel-options>>
* <<server-tcp-level-configurations-event-wire-logger>>
* <<server-tcp-level-configurations-event-loop-group>>

[[server-tcp-level-configurations-channel-options]]
=== Setting Channel Options

By default, the `TCP` server is configured with the following options:

====
[source,java,indent=0]
./../../main/java/reactor/netty/tcp/TcpServerBind.java
----
include::{sourcedir}/reactor/netty/tcp/TcpServerBind.java[lines=126..133]
----
====

If additional options are necessary or changes to the current options, you can apply the following configuration:

====
[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
====

You can find more about `Netty` channel options at the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[server-tcp-level-configurations-event-wire-logger]]
=== Using a Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.tcp.TcpServer` level to `DEBUG`
and apply the following configuration;

====
[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .wiretap(true) <1>
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
<1> Enables the wire logging
====

[[server-tcp-level-configurations-event-loop-group]]
=== Using an Event Loop Group

By default, the `TCP` server uses an "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods.

The default configuration for the `Event Loop Group` is the following:

====
[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=691..711]
----
====

If changes to the these settings are needed, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.DisposableServer;
import reactor.netty.resources.LoopResources;
import reactor.netty.tcp.TcpServer;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        DisposableServer server =
                TcpServer.create()
                         .runOn(loop)
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
====

== SSL/TLS

When you need SSL or TLS, you can apply the configuration shown in the next listing.
By default, if `OpenSSL` is available,
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
provider is used as a provider. Otherwise
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[`SslProvider.JDK`] is used.
Switching the provider can be done through
https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
or by setting `-Dio.netty.handler.ssl.noOpenSsl=true`.

The following example uses `SslContextBuilder`:

====
[source,java]
----
import io.netty.handler.ssl.SslContextBuilder;
import reactor.netty.DisposableServer;
import reactor.netty.tcp.TcpServer;
import java.io.File;

public class Application {

    public static void main(String[] args) {
        DisposableServer server =
                TcpServer.create()
                         .secure(spec ->
                                 SslContextBuilder.forServer(new File("certificate.crt"),
                                                             new File("private.key")))
                         .bindNow();

        server.onDispose()
              .block();
    }
}
----
====
