:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[udp-client]]
= UDP Client

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`].
It hides most of the Netty functionality that is required to create a `UDP` client
and adds Reactive Streams backpressure.

== Connecting and Disconnecting

To connect the UDP client to a given endpoint, you must create and configure a
{javadoc}/reactor/netty/udp/UdpClient.html[UdpClient] instance.
By default, the host is configured for `localhost` and the port is `12012`.
The following example shows how to create and connect a UDP client:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()                            <1>
                         .connectNow(Duration.ofSeconds(30)); <2>

        connection.onDispose()
                  .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`]
instance that is ready for configuring.
<2> Connects the client in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/Connection.html[`Connection`]
offers a simple connection API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the client down in a blocking fashion.

=== Host and Port

To connect to a specific `host` and `port`, you can apply the following configuration to the `UDP` client:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com") <1>
                         .port(80)            <2>
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
<1> Configures the `host` to which this client should connect
<2> Configures the `port` to which this client should connect
====

== Writing Data

To send data to a given peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpOutbound.html[`UdpOutbound`],
to be able to write data.

The following example shows how to send `hello`:

====
[source,java]
----
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;

import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((udpInbound, udpOutbound) -> udpOutbound.sendString(Mono.just("hello"))) <1>
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
<1> Sends `hello` string to the remote peer.
====

== Consuming Data

To receive data from a given peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpInbound.html[`UdpInbound`],
to be able to read data.
The following example shows how to consume data:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .handle((udpInbound, udpOutbound) -> udpInbound.receive().then()) <1>
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
<1> Receives data from a given peer
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `UDP` client:

* `doOnConnect`: Invoked when the channel is about to connect.
* `doOnConnected`: Invoked after the channel has been connected.
* `doOnDisconnected`: Invoked after the channel has been disconnected.
* `doOnLifecycle`: Sets up all lifecycle callbacks.

The following example uses the `doOnConnected` method:

====
[source,java]
----
import io.netty.handler.codec.LineBasedFrameDecoder;
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .doOnConnected(conn -> conn.addHandler(new LineBasedFrameDecoder(8192))) <1>
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
<1> The Netty pipeline is extended with `LineBasedFrameDecoder` when the channel has been connected.
====

== Connection Configurations

This section describes three kinds of configuration that you can use at the TCP level:

* <<client-udp-connection-configurations-channel-options>>
* <<client-udp-connection-configurations-wire-logger>>
* <<client-udp-connection-configurations-event-loop-group>>

[[client-udp-connection-configurations-channel-options]]
=== Channel Options

By default, the `UDP` client is configured with the following options:

====
[source,java,indent=0]
./../../main/java/reactor/netty/udp/UdpClient.java
----
include::{sourcedir}/reactor/netty/udp/UdpClient.java[lines=429..431]
----
====

If you need additional options or need to change the current options, you can apply the following configuration:

====
[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
====

You can find more about Netty channel options at the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[client-udp-connection-configurations-wire-logger]]
=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.udp.UdpClient` level to `DEBUG`
and apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .wiretap(true) <1>
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
<1> Enables the wire logging
====

[[client-udp-connection-configurations-event-loop-group]]
=== Event Loop Group

By default, the UDP client uses "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[`LoopResources`]`#create`
methods.

The following listing shows the default configuration for the "`Event Loop Group`":

====
[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=72..92]
----
====

If you need changes to the these settings, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.LoopResources;
import reactor.netty.udp.UdpClient;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        Connection connection =
                UdpClient.create()
                         .host("example.com")
                         .port(80)
                         .runOn(loop)
                         .connectNow(Duration.ofSeconds(30));

        connection.onDispose()
                  .block();
    }
}
----
====
