:sourcedir: ./../../main/java
:javadoc: https://projectreactor.io/docs/netty/release/api

[[udp-server]]
= UDP Server

Reactor Netty provides the easy-to-use and easy-to-configure
{javadoc}/reactor/netty/udp/UdpServer.html[`UdpServer`].
It hides most of the Netty functionality that is required to create a `UDP` server
and adds `Reactive Streams` backpressure.

== Starting and Stopping

To start a UDP server, a {javadoc}/reactor/netty/udp/UdpServer.html[UdpServer]
instance has to be created and configured.
By default, the host is configured to be `localhost` and the port is `12012`.
The following example shows how to create and start a UDP server:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()                         <1>
                         .bindNow(Duration.ofSeconds(30)); <2>

        server.onDispose()
              .block();
    }
}
----
<1> Creates a {javadoc}/reactor/netty/udp/UdpServer.html[`UdpServer`]
instance that is ready for configuring.
<2> Starts the server in a blocking fashion and waits for it to finish initializing.
====

The returned {javadoc}/reactor/netty/Connection.html[`Connection`]
offers a simple server API, including to {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`],
which shuts the server down in a blocking fashion.

=== Host and Port

In order to serve on a specific host and port, you can apply the following configuration to the `UDP` server:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .host("localhost") <1>
                         .port(8080)        <2>
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
<1> Configures the `UDP` server host
<2> Configures the `UDP` server port
====

== Writing Data

To send data to the remote peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpOutbound.html[`UdpOutbound`],
to be able to write data.
The following example shows how to send `hello`:

====
[source,java]
----
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.socket.DatagramPacket;
import io.netty.util.CharsetUtil;
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;

import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .handle((in, out) ->
                             out.sendObject(
                                 in.receiveObject()
                                   .map(o -> {
                                       if (o instanceof DatagramPacket) {
                                           DatagramPacket p = (DatagramPacket) o;
                                           ByteBuf buf = Unpooled.copiedBuffer("hello", CharsetUtil.UTF_8);
                                           return new DatagramPacket(buf, p.sender()); <1>
                                       }
                                       else {
                                           return Mono.error(
                                               new Exception("Unexpected type of the message: " + o));
                                       }
                                   })))
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
<1> Sends a `hello` string to the remote peer
====

== Consuming Data

To receive data from a remote peer, you must attach an I/O handler.
The I/O handler has access to {javadoc}/reactor/netty/udp/UdpInbound.html[`UdpInbound`],
to be able to read data.
The following example shows how to consume data:

====
[source,java]
----
import io.netty.channel.socket.DatagramPacket;
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;

import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .handle((in, out) ->
                             out.sendObject(
                                 in.receiveObject()
                                   .map(o -> {
                                       if (o instanceof DatagramPacket) {
                                           DatagramPacket p = (DatagramPacket) o;
                                           return new DatagramPacket(p.content().retain(), p.sender()); <1>
                                       }
                                       else {
                                           return Mono.error(new Exception("Unexpected type of the message: " + o));
                                       }
                                   })))
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
<1> Receives data from the remote peer
====

== Lifecycle Callbacks

The following lifecycle callbacks are provided to let you extend the `UDP` server:

* `doOnBind`: Invoked when the server channel is about to bind.
* `doOnBound`: Invoked when the server channel is bound.
* `doOnUnbound`: Invoked when the server channel is unbound.
* `doOnLifecycle`: Sets up all lifecycle callbacks.

The following example uses the `doOnBound` method:

====
[source,java]
----
import io.netty.handler.codec.LineBasedFrameDecoder;
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .doOnBound(conn -> conn.addHandler(new LineBasedFrameDecoder(8192))) <1>
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
<1> `Netty` pipeline is extended with `LineBasedFrameDecoder` when the server channel is bound.
====

== Connection Configurations

This section describes three kinds of configuration that you can use at the TCP level:

* <<server-udp-connection-configurations-channel-options>>
* <<server-udp-connection-configurations-wire-logger>>
* <<server-udp-connection-configurations-event-loop-group>>

[[server-udp-connection-configurations-channel-options]]
=== Channel Options

By default, the `UDP` server is configured with the following options:

====
[source,java,indent=0]
./../../main/java/reactor/netty/udp/UdpServer.java
----
include::{sourcedir}/reactor/netty/udp/UdpServer.java[lines=476..478]
----
====

If you need additional options or need to change the current options, you can apply the following configuration:

====
[source,java]
----
import io.netty.channel.ChannelOption;
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
====

For more about Netty channel options, see the following links:

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[server-udp-connection-configurations-wire-logger]]
=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers has to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `reactor.netty.udp.UdpServer` level to `DEBUG`
and apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        Connection server =
                UdpServer.create()
                         .wiretap(true) <1>
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
<1> Enables the wire logging
====

[[server-udp-connection-configurations-event-loop-group]]
=== Event Loop Group

By default, the UDP server uses "`Event Loop Group,`" where the number of the worker threads equals the number of
processors available to the runtime on initialization (but with a minimum value of 4). When you need a different configuration,
you can use one of the {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create`
methods.

The default configuration for the "`Event Loop Group`" is the following:

====
[source,java,indent=0]
./../../main/java/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=75..95]
----
====

If you need changes to the these settings, you can apply the following configuration:

====
[source,java]
----
import reactor.netty.Connection;
import reactor.netty.resources.LoopResources;
import reactor.netty.udp.UdpServer;
import java.time.Duration;

public class Application {

    public static void main(String[] args) {
        LoopResources loop = LoopResources.create("event-loop", 1, 4, true);
        Connection server =
                UdpServer.create()
                         .runOn(loop)
                         .bindNow(Duration.ofSeconds(30));

        server.onDispose()
              .block();
    }
}
----
====
