== Proxy Support

Reactor Netty supports the proxy functionality provided by Netty and provides a way
to specify `non proxy hosts` through the {javadoc}/reactor/netty/tcp/ProxyProvider.html[`ProxyProvider`] builder.

// tag::proxy-connect-method[]
Netty's HTTP proxy support always uses `CONNECT` method in order to establish a tunnel to the specified proxy regardless of the scheme that is used `http` or `https`.
(More information: https://github.com/netty/netty/issues/10475[Netty enforce HTTP proxy to support HTTP CONNECT method]).
Some proxies might not support `CONNECT` method when the scheme is `http` or might need to be configured in order to support this way of communication.
Sometimes this might be the reason for not being able to connect to the proxy. Consider checking the proxy documentation
whether it supports or needs an additional configuration in order to support `CONNECT` method.
// end::proxy-connect-method[]

NOTE: When a proxy is configured and no custom DNS resolver has been specified, Reactor Netty automatically uses
{nettyjavadoc}/io/netty/resolver/NoopAddressResolverGroup.html[`NoopAddressResolverGroup`] to skip client-side DNS
resolution and delegate it to the proxy. If a custom DNS resolver is explicitly configured (e.g. the JVM built-in resolver
via `DefaultAddressResolverGroup.INSTANCE` or via the `resolver(...)` method), Reactor Netty respects that configuration
and does not override it. In that case, the configured resolver must be able to resolve the target hostname on the client side,
even when using a proxy.

The following example uses `ProxyProvider`:

{examples-link}/proxy/Application.java
[%unbreakable]
----
include::{examples-dir}/proxy/Application.java[lines=18..42]
----
<1> Configures the connection establishment timeout to 20 seconds.


// tag::proxy-when-method[]
The `proxyWhen(...)` method allows for dynamic proxy configuration.

- `proxyWhen(...)` takes an `HttpClientConfig` and enables setting a proxy for each individual HTTP request, providing flexibility to choose different proxies depending on the request.
- Once the proxy is set using `proxyWhen(...)`, any previous proxy settings via `proxy(...)` or `noProxy()` will be ignored.
// end::proxy-when-method[]
{examples-link}/proxy/deferred/Application.java
[%unbreakable]
----
include::{examples-dir}/proxy/deferred/Application.java[lines=18..55]
----