== Proxy Support

Reactor Netty supports the proxy functionality provided by Netty and provides a way
to specify `non proxy hosts` through the {javadoc}/reactor/netty/tcp/ProxyProvider.html[`ProxyProvider`] builder.

// tag::proxy-connect-method[]
Netty's HTTP proxy support always uses `CONNECT` method in order to establish a tunnel to the specified proxy regardless of the scheme that is used `http` or `https`.
(More information: https://github.com/netty/netty/issues/10475[Netty enforce HTTP proxy to support HTTP CONNECT method]).
Some proxies might not support `CONNECT` method when the scheme is `http` or might need to be configured in order to support this way of communication.
Sometimes this might be the reason for not being able to connect to the proxy. Consider checking the proxy documentation
whether it supports or needs an additional configuration in order to support `CONNECT` method.
// end::proxy-connect-method[]

The following example uses `ProxyProvider`:

{examples-link}/proxy/Application.java
[%unbreakable]
----
include::{examples-dir}/proxy/Application.java[lines=18..42]
----
<1> Configures the connection establishment timeout to 20 seconds.
