:formattersourcedir: {core}/src/main/java

=== Wire Logger

Reactor Netty provides wire logging for when the traffic between the peers needs to be inspected.
By default, wire logging is disabled.
To enable it, you must set the logger `{wirelogger}` level to `DEBUG`
and apply the following configuration:

[source,java,indent=0]
.{examples-dir}/wiretap/Application.java
[%unbreakable]
----
include::{examples-dir}/wiretap/Application.java[lines=18..35]
----
<1> Enables the wire logging

[[wire-logger-formatters]]
==== Wire Logger formatters
Reactor Netty supports 3 different formatters:

- {javadoc}/reactor/netty5/transport/logging/AdvancedBufferFormat.html#HEX_DUMP[AdvancedBufferFormat#HEX_DUMP] - the default

[source,java,indent=0]
.{sourcedir}/reactor/netty5/transport/logging/AdvancedByteBufFormat.java
[%unbreakable]
----
include::{formattersourcedir}/reactor/netty5/transport/logging/AdvancedBufferFormat.java[lines=46..74]
----

- {javadoc}/reactor/netty5/transport/logging/AdvancedBufferFormat.html#SIMPLE[AdvancedBufferFormat#SIMPLE]

[source,java,indent=0]
.{sourcedir}/reactor/netty5/transport/logging/AdvancedByteBufFormat.java
[%unbreakable]
----
include::{formattersourcedir}/reactor/netty5/transport/logging/AdvancedBufferFormat.java[lines=33..44]
----

- {javadoc}/reactor/netty5/transport/logging/AdvancedBufferFormat.html#TEXTUAL[AdvancedBufferFormat#TEXTUAL]

[source,java,indent=0]
.{sourcedir}/reactor/netty5/transport/logging/AdvancedByteBufFormat.java
[%unbreakable]
----
include::{formattersourcedir}/reactor/netty5/transport/logging/AdvancedBufferFormat.java[lines=76..92]
----


When you need to change the default formatter you can configure it as follows:

[source,java,indent=0]
.{examples-dir}/wiretap/custom/Application.java
[%unbreakable]
----
include::{examples-dir}/wiretap/custom/Application.java[lines=18..38]
----
<1> Enables the wire logging,
{javadoc}/reactor/netty5/transport/logging/AdvancedBufferFormat.html#TEXTUAL[AdvancedBufferFormat#TEXTUAL] is used for
printing the content.
