name: Check Reactor Netty 1.2.x with Netty 4.1 and 4.2 SNAPSHOTS

on:
  schedule:
    - cron: "0 14 * * *"
permissions: {}
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        transport: [native, nio]
        exclude:
          # excludes native on Windows (there's none)
          - os: windows-2022
            transport: native
          # macOS - https://github.com/netty/netty/issues/9689
          - os: macos-14
            transport: native

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: '1.2.x'
      - name: Set up JDK 1.8
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a
        with:
            distribution: 'graalvm'
            java-version: '17.0.12'
      - name: Build with Gradle against Netty 4.1
        run: ./gradlew clean check -x :reactor-netty-core:java17Test --no-daemon -PforceTransport=${{ matrix.transport }} -PforceNettyVersion='4.1.137.Final-SNAPSHOT' -PparallelTests
      - name: GraalVM smoke tests against Netty 4.1
        run: ./gradlew :reactor-netty-graalvm-smoke-tests:nativeTest --no-daemon -PforceTransport=${{ matrix.transport }} -PforceNettyVersion='4.1.137.Final-SNAPSHOT'
      - name: Build with Gradle against Netty 4.2
        run: ./gradlew clean check -x :reactor-netty-core:java17Test --no-daemon -PforceTransport=${{ matrix.transport }} -PforceNettyVersion='4.2.17.Final-SNAPSHOT' -PparallelTests
      - name: GraalVM smoke tests against Netty 4.2
        run: ./gradlew :reactor-netty-graalvm-smoke-tests:nativeTest --no-daemon -PforceTransport=${{ matrix.transport }} -PforceNettyVersion='4.2.17.Final-SNAPSHOT'
