name: publish
on:
  push:
    branches: # For branches, better to list them explicitly than regexp include
      - main-internal
permissions: read-all

jobs:
  # General job notes: we DON'T want to cancel any previous runs, especially in the case of a "back to snapshots" build right after a release push
  # We specify the ubuntu version to minimize the chances we have to deal with a migration during a release
  reactor-netty-core:
    # Notes on reactor-netty-core: this job has no access to secrets, only github token. As a result, all non-core actions are centralized here
    name: reactor-netty-core
    runs-on: ubuntu22-2-8
    outputs:
      versionType: ${{ steps.version.outputs.versionType }}
      fullVersion: ${{ steps.version.outputs.fullVersion }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'zulu'
          java-version: |
            8
            11
            17
      - name: interpret version
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
        id: version
        #we only run the qualifyVersionGha task so that no other console printing can hijack this step's output
        #output: versionType, fullVersion
        #fails if versionType is BAD, which interrupts the workflow
        run: ./gradlew qualifyVersionGha
      - name: run reactor-netty-core checks
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
        id: reactor-netty-core-checks
        run: ./gradlew reactor-netty-core:check -x :reactor-netty-core:java17Test -x :reactor-netty-core:java11Test
  reactor-netty-http:
    # Notes on reactor-netty-http: this job has no access to secrets, only github token. As a result, all non-core actions are centralized here
    name: reactor-netty-http
    runs-on: ubuntu22-2-8
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'zulu'
          java-version: |
            8
            17
      - name: run reactor-netty-http checks
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
        id: reactor-netty-http-checks
        run: ./gradlew reactor-netty-http:check
  reactor-netty-http-brave:
    # Notes on reactor-netty-http-brave: this job has no access to secrets, only github token. As a result, all non-core actions are centralized here
    name: reactor-netty-http-brave
    runs-on: ubuntu22-2-8
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'zulu'
          java-version: |
            8
            17
      - name: run reactor-netty-http-brave checks
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
        id: reactor-netty-http-brave-checks
        run: ./gradlew reactor-netty-http-brave:check
  reactor-netty-quic:
    # Notes on reactor-netty-quic: this job has no access to secrets, only github token. As a result, all non-core actions are centralized here
    name: reactor-netty-quic
    runs-on: ubuntu22-2-8
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'zulu'
          java-version: |
            8
            17
      - name: run reactor-netty-quic checks
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
        id: reactor-netty-quic-checks
        run: ./gradlew reactor-netty-quic:check

  #deploy the snapshot artifacts to Artifactory
  deploySnapshot:
    name: deploySnapshot
    runs-on: ubuntu22-2-8
    needs: [ reactor-netty-core, reactor-netty-http, reactor-netty-http-brave, reactor-netty-quic ]
    if: needs.reactor-netty-core.outputs.versionType == 'SNAPSHOT'
    environment: snapshots
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: setup java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'zulu'
          java-version: |
            8
            11
            17
      - name: deploy
        env:
          COMMERCIAL_REPO_USERNAME: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          COMMERCIAL_REPO_PASSWORD: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
          COMMERCIAL_RELEASE_REPO_URL: ${{vars.COMMERCIAL_RELEASE_REPO_URL}}
          COMMERCIAL_SNAPSHOT_REPO_URL: ${{vars.COMMERCIAL_SNAPSHOT_REPO_URL}}
          ORG_GRADLE_PROJECT_artifactory_publish_username: ${{secrets.COMMERCIAL_ARTIFACTORY_USERNAME}}
          ORG_GRADLE_PROJECT_artifactory_publish_password: ${{secrets.COMMERCIAL_ARTIFACTORY_PASSWORD}}
        run: |
          ./gradlew assemble artifactoryPublish -x :docs:antora -Partifactory_publish_contextUrl=https://usw1.packages.broadcom.com -Partifactory_publish_repoKey=spring-enterprise-maven-dev-local
